app/helpers/react_on_rails_helper.rb
lib/react_on_rails.rb
lib/react_on_rails/configuration.rb
lib/react_on_rails/react_renderer.rb
spec/dummy/config/initializers/react_on_rails.rb
spec/react_on_rails/configuration_spec.rb

https://github.com/shakacode/react_on_rails/issues/9
Pair with Mario(@mapreal19)

Add React on Rails configuration

---

.coveralls.yml
.travis.yml
README.md
react_on_rails.gemspec
spec/react_on_rails_spec.rb

Add coveralls.io integration for code coverage reporting.
Add build status badge for Travis-CI
Add dependency/security status badge for gemnasium.

Code coverage and status badges

---

app/helpers/react_on_rails_helper.rb
lib/react_on_rails/react_renderer.rb
spec/dummy/app/views/pages/_header.erb
spec/dummy/app/views/pages/render_js.html.erb
spec/dummy/app/views/pages/server_side_hello_world.html.erb
spec/dummy/client/app/components/HelloWorld.jsx
spec/dummy/config/initializers/react_on_rails.rb
spec/dummy/config/routes.rb

* Fixes crash using render_js and no console msgs
* Fixes missing html_safe when calling content_tag

Fix no console message on server crash

---

README.md
app/helpers/react_on_rails_helper.rb
lib/react_on_rails.rb
lib/react_on_rails/configuration.rb
lib/react_on_rails/react_renderer.rb
lib/react_on_rails/server_rendering_pool.rb
react_on_rails.gemspec
spec/dummy/Gemfile.lock
spec/dummy/config/initializers/react_on_rails.rb

Branch for fixing #28 
Added configuration options:
*  config.server_renderer_pool_size
*  config.server_renderer_timeout

WIP for #28 -- not working

---

app/assets/javascripts/react_on_rails.js

handleError was shared between client & server but prior implementation assumed server.
cleaned up, no spacing issues, no ordering issues.

rewrote function due to problem with handleError

---

react_on_rails.gemspec

Changed gem's dependency from Rails >= 4.0.0  to >= 3.2

Support for rails 3.2+

---

.simplecov
Rakefile
spec/dummy/spec/rails_helper.rb
spec/dummy/spec/simplecov_helper.rb
spec/react_on_rails_spec.rb
spec/simplecov_helper.rb

Tune up Coveralls and SimpleCov

---

.coveralls.yml
.dockerignore
.gitignore
.jscsrc
.scss-lint.yml
.travis.yml
Dockerfile
Dockerfile_ci
Dockerfile_tests
Rakefile
docker-compose.yml
docs/Contributing.md
react_on_rails.gemspec
spec/dummy-react-013/config/routes.rb
spec/dummy/Gemfile
spec/dummy/Gemfile.lock
spec/dummy/bin/setup
spec/dummy/config/routes.rb

Add docker-compose ci and tests containers that run xvfd with headless browser testing with selenium an firefox
Set travis.yml to run docker-compose ci for complete linting and tests
Clean up spec/dummy/bin/setup
Add config within spec/dummy/Gemfile to eval gemspec and install gems from gemspec during bundle intall --path /spec/dummy/Gemfile.
Add info about new additions to contributors README.

Update docker for CI, Test, and Linting

---

app/helpers/react_on_rails_helper.rb
spec/dummy/.rspec
spec/dummy/spec/helpers/react_on_rails_helper_spec.rb

A reconciled version of PR #43

Add unit tests to helper

---

lib/react_on_rails/server_rendering_pool.rb

Added details on how to avoid this message.
Fixes #76

Detailed message to console if no server js file

---

app/helpers/react_on_rails_helper.rb
lib/react_on_rails/configuration.rb
lib/react_on_rails/server_rendering_pool.rb

@robwise let me know if I have this right.  Was pretty straight forward, just had to make sure not to include the 'extra stuff'.

Server reload bundle fix

---

README.md
docs/linters.md
lib/generators/react_on_rails/install_generator.rb
lib/generators/react_on_rails/templates/no_redux/base/client/package.json.tt
lib/generators/react_on_rails/templates/redux/base/client/package.json.tt
spec/react_on_rails/generators/install_generator_spec.rb

Now you have to specify --linters or -L to add linters

Linters are not the default

---

lib/generators/react_on_rails/templates/redux/base/client/app/lib/middlewares/loggerMiddleware.js

We can just use `JSON.stringify` here

Refactor logger middleware generation

---

README.md
docs/additional_reading/heroku_deployment.md
lib/generators/react_on_rails/heroku_deployment_generator.rb
lib/generators/react_on_rails/install_generator.rb
lib/generators/react_on_rails/templates/heroku_deployment/Procfile
lib/generators/react_on_rails/templates/heroku_deployment/config/puma.rb
spec/react_on_rails/generators/install_generator_spec.rb

Add Puma to Heroku Generator, enable the option to turn it on or off, and default it to off.

Make Heroku Generator Optional

---

lib/generators/react_on_rails/base_generator.rb
spec/react_on_rails/generators/install_generator_spec.rb
spec/react_on_rails/support/generator_spec_helper.rb
spec/react_on_rails/support/shared_examples/base_generator_examples.rb

Fix generator. Do not remove jQuery plugins from application.js

---

lib/generators/react_on_rails/base_generator.rb
lib/generators/react_on_rails/templates/base/base/app/views/hello_world/index.html.erb.tt
spec/react_on_rails/support/shared_examples/base_generator_examples.rb

#133 unnecessary gem if not server rendering

---

lib/generators/react_on_rails/base_generator.rb
spec/react_on_rails/generators/install_generator_spec.rb
spec/react_on_rails/support/shared_examples/base_generator_examples.rb

Just comment out incompatible requires. Refers to #140

Fix application.js incorrect overwritten issue

---

README.md
app/assets/javascripts/react_on_rails.js
docs/additional_reading/webpack.md
docs/webpack.md
lib/generators/react_on_rails/templates/base/server_rendering/client/webpack.server.rails.config.js

#134 - Fix server react config and add necessary warning and document.

---

lib/generators/react_on_rails/base_generator.rb
lib/generators/react_on_rails/templates/base/base/lib/tasks/assets.rake.tt
spec/react_on_rails/support/shared_examples/base_generator_examples.rb

Don't copy incorrect command into assets.rake when skipping server rendering

---

Gemfile

This should fix the double-require issue as well (third item in https://github.com/shakacode/react_on_rails/issues/149)

Fix Gemfile dependencies and add comment

---

CHANGELOG.md

This is for the first item of  #149.
Please add more necessary details according to the suggested format described here: http://keepachangelog.com/
cc @justin808 @robwise

Add CHANGELOG.md to include all release notes based on versions.

---

lib/generators/react_on_rails/templates/base/base/client/package.json.tt

Updated the package.json.tt matcher for 2.0.0

Updated the version matcher for 2.0.0

---

CHANGELOG.md

Small change to improve the readability of the code blocks in the changelog

Cleaned up code blocks

---

lib/generators/react_on_rails/generator_messages.rb
spec/react_on_rails/generators/generator_messages_spec.rb

- Added new tests to Generator Messages.
- Fixed color bug with rainbow by using the orange RGB value instead. #211 
- Added require simplecov helper.

Add Tests to Generator Messages

---

lib/generators/react_on_rails/templates/base/base/client/server.js

Changes the output message slightly
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/227)

Minor change to generated dev server

---

lib/generators/react_on_rails/templates/dev_tests/spec/simplecov_helper.rb

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/228)

Fix where coverage folder is being output for generated apps

---

CHANGELOG.md
docs/releasing.md
lib/generators/react_on_rails/install_generator.rb
lib/react_on_rails.rb
lib/react_on_rails/git_utils.rb
lib/react_on_rails/utils.rb
rakelib/release.rake
rakelib/task_helpers.rb
script/release

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/233)

Add rake script for releasing new verison

---

spec/dummy/client/npm-shrinkwrap.json
spec/dummy/client/package.json

ROR in SERVER PRERENDERING
Encountered error: "TypeError: Cannot read property 'name' of undefined"
when prerendering N/A (server_render_js called) with props:
js_code was:
(function() {
var htmlResult = '';
var consoleReplayScript = '';
var hasErrors = false;
try {
htmlResult =
(function() {
return
ReactOnRails.getComponent('HelloString').component.world();
})();
} catch(e) {
htmlResult = ReactOnRails.handleError({e: e, name: null,
jsCode:
'ReactOnRails.getComponent(\'HelloString\').component.world()',
serverSide: true});
hasErrors = true;
}
consoleReplayScript = ReactOnRails.buildConsoleReplay();
return JSON.stringify({
html: htmlResult,
consoleReplayScript: consoleReplayScript,
hasErrors: hasErrors
});
})()
Object.<anonymous> ((execjs):27066:58)
Object.<anonymous> ((execjs):27075:31) …

Trying update dependencies, fails server rendering

---

react_on_rails.gemspec

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/248)

Added Foreman as a dependency.

---

lib/generators/USAGE

Update the generator help output `rails generate react_on_rails:install -h`
- Change text node-server-hot to express-server. 
This was changed in #210
- Fix indentation.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/255)

Update Generator Help

---

README.md

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/260)

Corrected few typos in README.md

---

docs/additional_reading/react-and-redux.md
lib/generators/react_on_rails/templates/redux/base/client/app/bundles/HelloWorld/reducers/index.jsx
lib/generators/react_on_rails/templates/redux/base/client/app/bundles/HelloWorld/store/helloWorldStore.jsx

Missing "i".
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/267)

Fix typo initalState

---

.jscsrc
lib/generators/react_on_rails/templates/base/base/client/webpack.client.hot.config.js.tt
lib/generators/react_on_rails/templates/redux/base/client/app/bundles/HelloWorld/reducers/index.jsx
lib/generators/react_on_rails/templates/redux/base/client/app/lib/middlewares/loggerMiddleware.js
node_package/src/ReactOnRails.js
node_package/src/clientStartup.js
node_package/src/generatorFunction.js
node_package/tests/ReactOnRails.test.js
node_package/tests/buildConsoleReplay.test.js
spec/dummy/Gemfile.lock

JSCS 2.9 revealed a bunch of lint issues, including one bug in the
linter:
https://github.com/jscs-dev/node-jscs/issues/2137
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/278)

Fix linting issues

---

CHANGELOG.md
lib/generators/react_on_rails/base_generator.rb
lib/generators/react_on_rails/react_with_redux_generator.rb
spec/react_on_rails/generators/install_generator_spec.rb

- Add info for hot reloading server npm cmd.
- Remove duplicate code from redux generator
helpful msg because base now prints the same msg.
- Update tests to reflect changes.
***
`rails generate react_on_rails:install`
***
#277
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/279)

Update Base Generator Helpful Message

---

lib/generators/react_on_rails/templates/base/base/client/webpack.client.rails.config.js

Pretty sure this comment was meant to include `:client`?
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/284)

fix build comment in generator

---

PROJECTS.md
README.md

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/288)

Add projects using React on Rails.

---

CHANGELOG.md

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/297)

fix link to PR in changelog

---

CHANGELOG.md
README.md

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/300)

Update README.md and CHANGELOG.md for 3.0.5

---

PROJECTS.md

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/302)

add Pivotal Tracker to projects page

---

README.md
lib/generators/USAGE

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/308)

Correct some typo in README.md and USAGE。

---

docs/tutorial-v2.md

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/329)

Minor typo correction

---

CHANGELOG.md
NEWS.md
README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/334)

Updated CHANGELOG.md and README.md, addeed NEWS.md

---

CHANGELOG.md
NEWS.md
README.md
app/helpers/react_on_rails_helper.rb
spec/dummy/Gemfile.lock
spec/dummy/spec/helpers/react_on_rails_helper_spec.rb

When no props passed to react_component, we got an invalid deprecation
message.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/336)

Fixed invalid deprecation message when no props

---

README.md
docs/additional_reading/hot-reloading-rails-development.md
spec/dummy/Gemfile.lock
spec/dummy/Procfile.hot
spec/dummy/app/assets/javascripts/application_static.js
spec/dummy/app/assets/stylesheets/application_static.css.scss
spec/dummy/config/initializers/assets.rb
spec/dummy/spec/rails_helper.rb

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/339)

Doc updates

---

docs/additional-reading/installation-overview.md

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/344)

Fix small typo in installation-overview.md

---

CHANGELOG.md
README.md
spec/dummy/spec/features/integration_spec.rb

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/348)

Fix component typos

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/349)

Update README link to contributing.md

---

CHANGELOG.md
README.md
app/helpers/react_on_rails_helper.rb
spec/dummy/app/views/pages/server_side_hello_world_with_options.html.erb
spec/dummy/config/initializers/react_on_rails.rb
spec/dummy/spec/helpers/react_on_rails_helper_spec.rb

* Much tighter checking of parameters now.
* Also updated the CHANGELOG and README
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/352)

Named parameters for view helper react_component

---

PROJECTS.md

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/356)

Add CFS to commercial products

---

KUDOS.md

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/357)

Added quote

---

README.md

Teeny-tiny change, but just saw that you guys are on 5.1 and I figured you wanted this in the README.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/363)

Updated README to use version 5

---

README.md
docs/contributor-info/contributing.md
docs/contributor-info/releasing.md
spec/dummy/Gemfile

Fixes #376
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/377)

Updating docs and gems

---

lib/react_on_rails/server_rendering_pool.rb

NOTE: Similar bugs may exist elsewhere in the code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/386)

Fix file exists check for server bundle, which returns true for a dir.

---

lib/generators/react_on_rails/templates/base/base/package.json.tt

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/393)

Update build:client in generator to correctly have closing parenthesis

---

PROJECTS.md

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/395)

Add Apprentus to PROJECTS.md

---

README.md

Just saw a couple typos while first reading through, figured I'd submit a little PR :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/407)

Typo Cleanup and indentation adjustment in README

---

spec/dummy/client/server-rails-hot.js

Small fix for something I've also extensively done in the past :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/422)

Use the hotRailsPort on devServer listen

---

CHANGELOG.md
docs/additional-reading/babel.md
docs/additional-reading/node-server-rendering.md
docs/additional-reading/rails-assets.md
docs/additional-reading/turbolinks.md
docs/additional-reading/webpack-dev-server.md

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/433)

Final doc updates before v6

---

docs/additional-reading/react-router.md

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/466)

fix link to server rendering in router docs

---

README.md

fix typo :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/487)

fix(typo) remove duplicated word in readme

---

lib/generators/react_on_rails/templates/base/base/client/REACT_ON_RAILS_CLIENT_README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/492)

Fixes typo

---

CONTRIBUTING.md
README.md
docs/contributor-info/releasing.md

This seems to make it show more prominently when making new issues or
PRs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/502)

Move CONTRIBUTING.MD to project top level

---

docs/tutorial.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/506)

updated tutorial to v6

---

.gitignore
lib/generators/USAGE
lib/generators/react_on_rails/base_generator.rb
spec/dummy/client/webpack.client.base.config.js
spec/dummy/client/webpack.client.rails.build.config.js
spec/react_on_rails/generators/install_generator_spec.rb
spec/react_on_rails/support/shared_examples/base_generator_examples.rb

While I was following and reading through the tutorial of the `react_on_rails` gem,
I've noticed these missed bits.
Old links, old names etc.
Though nothing of importance.
🍒
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/514)

Misc fixes (unimportant)

---

lib/generators/react_on_rails/templates/node/base/client/node/server.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/528)

Address linting issues

---

Gemfile
lib/generators/react_on_rails/base_generator.rb
lib/generators/react_on_rails/templates/base/base/config/initializers/react_on_rails.rb.tt
spec/dummy/Gemfile
spec/dummy/Gemfile.lock
spec/dummy/config/initializers/react_on_rails.rb

mini_racer is way faster
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/526)

Update from therubyracer to mini_racer

---

.bookignore
NEWS.md
README.md
SUMMARY.md
book.json

#331
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/534)

Integrate with Gitbook

---

README.md

I was looking at contributing but noticed the link was broken, so I updated it so it works.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/554)

Fix broken link to Contributing in Readme.

---

lib/generators/react_on_rails/templates/base/base/client/app/bundles/HelloWorld/components/HelloWorldWidget.jsx.tt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/559)

Fix comment typo in HelloWorldWidget [ci skip]

---

docs/additional-reading/hot-reloading-rails-development.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/558)

Fix a typo

---

CHANGELOG.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/561)

Fix markdown

---

.eslintrc
.jscsrc
node_package/src/clientStartup.js
node_package/src/handleError.js
node_package/tests/Authenticity.test.js
node_package/tests/ReactOnRails.test.js
node_package/tests/buildConsoleReplay.test.js
node_package/tests/helpers/test_helper.js
package.json

Here's the PR I promised. One possible change I was considering was including https://github.com/rstacruz/jsdom-global instead of partially rolling our own. That's up to you though.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/569)

fix naive global ReactOnRails references

---

README.md

The old url came to a 404 page.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/585)

Fix link to forum

---

PROJECTS.md

@justin808 Can you review this?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/588)

Fix broken link to Friends and Guests

---

README.md

This change breaks the first numbered list item into its own line, and adds code backticks around `bundle install`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/600)

Cleanup First Item of 'Getting Started'

---

node_package/src/clientStartup.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/611)

Fixes #610

---

docs/additional-reading/heroku-deployment.md

Addresses Issue #616.
React on Rails has been updated so this is no longer needed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/627)

Remove section on lib/tasks/asset.rake

---

spec/react_on_rails/generators/install_generator_spec.rb

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/633)

Fixed broken test

---

spec/dummy/client/server-rails-hot.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/637)

Fix spelling

---

CHANGELOG.md
README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/684)

6.4 changes to docs for removal of foreman from dependencies

---

node_package/src/clientStartup.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/703)

Small formatting tweak

---

docs/additional-reading/recommended-project-structure.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/731)

`bundle` in  `/client/app/bundle/comments` should be plural

---

PROJECTS.md

A step-by-step tutorial which shows you how to set up Hot Module Replacement in a Rails 5 app using react_on_rails. It's based on the [Hot Reloading README](https://github.com/shakacode/react_on_rails/blob/master/docs/additional-reading/hot-reloading-rails-development.md) and simplifies the process to just the basics, so even a beginner can get set up quickly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/740)

Add HMR tutorial to PROJECTS.md

---

CHANGELOG.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/745)

Fix reference to wrong PR in CHANGELOG

---

README.md
SUMMARY.md
docs/basics/i18n.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/743)

Update Docs for i18n

---

docs/basics/generator.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/783)

Update the tutorial link

---

app/helpers/react_on_rails_helper.rb
spec/dummy/Gemfile.lock
spec/dummy/client/yarn.lock
yarn.lock

Bug caused by not handling JSON.pretty_generate for strings.
TODO:
1. Add test
2. Add error handler if cannot parse the string with nice
message
3. Consider checking that if not a string then a Hash
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/784)

Fixes Crash in Development for String Props

---

spec/dummy/client/package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/805)

Add ^ to react-helmut

---

CHANGELOG.md
app/helpers/react_on_rails_helper.rb
spec/dummy/spec/helpers/react_on_rails_helper_spec.rb

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/824)

Return empty json when nil in json_safe_and_pretty

---

README.md

Hello,
I just installed react_on_rails in my project today and it's working great! Thanks for the time you put into this. Here's a couple minor changes in a README that looked off to me, perhaps because because you just released version 7 this week. 
* Reference version 7 in gemfile
* Reference "HelloWorld" component that generator created rather than "HelloWorldApp" component that I didn't find. 
Thanks again! 
Peter
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/825)

Suggested edits to README

---

docs/tutorial.md

Hi,
I installed react_on_rails just now. It's wonderful. Thanks! When I read your React on Rails Basic Tutorial, I realised small changes should be in the tutorial.
- version 7 in gemfile
- The first access should be http://localhost:5000/hello_world (port is not 3000)
Thank you.
Shinya
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/830)

Update React on Rails Basic Tutorial

---

spec/dummy/client/package.json
spec/dummy/client/webpack.client.rails.build.config.js
spec/dummy/client/webpack.client.rails.hot.config.js

- fix hot config bundle name
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/838)

use webpack-merge

---

docs/tutorial.md
spec/dummy/client/yarn.lock

The tutorial has been fully tested with react_on_rails 8.0.0.
Only **docs/tutorial.md** and **spec/dummy/client/yarn.lock** were changed.
It works with and without --redux.
It has been successfully deployed to heroku with and without --redux.
Heroku Deploys:
[https://hello-react-on-rails-8-0-0.herokuapp.com/](https://hello-react-on-rails-8-0-0.herokuapp.com/)
[https://react-on-rails-redux-gen-8-0-0.herokuapp.com/](https://react-on-rails-redux-gen-8-0-0.herokuapp.com/)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/840)

Updated tutorial.md for 8.0.0.beta.2

---

docs/additional-reading/heroku-deployment.md

Link to the dummy app to illustrate usage
Thanks for the great gem!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/853)

Docs: Provide example of overriding Heroku asset compilation

---

spec/dummy/Gemfile
spec/dummy/Gemfile.lock
spec/dummy/client/webpack.client.base.config.js
spec/dummy/client/webpack.client.rails.build.config.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/858)

Updated webpacker_lite to 2.0.3

---

lib/generators/react_on_rails/templates/base/base/config/initializers/react_on_rails.rb.tt
lib/react_on_rails/configuration.rb
spec/dummy/Gemfile.lock
spec/dummy/config/initializers/react_on_rails.rb

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/907)

Small doc fixes regarding i18n

---

CHANGELOG.md
lib/react_on_rails/utils.rb
spec/react_on_rails/utils_spec.rb

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/913)

Add missing `else` clause, ensuring hashed filename is used for Webpacker.

---

lib/generators/react_on_rails/templates/base/base/config/webpacker_lite.yml

Just fixed one line of `generators/react_on_rails/templates/base/base/config/webpacker_lite.yml`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/920)

Fix typo on webpacker_lite.yml

---

docs/additional-reading/hot-reloading-rails-development.md

The old file is dead
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/934)

Update filename and link

---

docs/basics/installation-overview.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/938)

Fix broken link to Tutorial.md

---

docs/basics/configuration.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/952)

fix  wrong syntax highlighting

---

docs/additional-reading/heroku-deployment.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/953)

Heroku deployment: db:setup before db:migrate

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/972)

Fixed README.md typo in SSR example

---

CHANGELOG.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/976)

Fix compare link in CHANGELOG.md

---

README.md
docs/tutorial.md

I also added some minor changes. Let me know if you think those should be changed in any way or are not needed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/980)

Update v9 references to v10

---

docs/tutorial.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/981)

Clarify tutorial scope; Explain exact gem version

---

Gemfile

[Gemnasium,](https://gemnasium.com/shakacode/react_on_rails) the service used by our project, to track the dependency shows the necessity of upgrading the Rails version
Changelog for the Rails changes can be found [here](https://github.com/rails/rails/compare/v5.1.2...v5.1.4).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/984)

Update Rails from 5.1.2 to 5.1.4

---

docs/tutorial.md

Otherwise it returns `Don't know how to build task 'generator' (see --tasks)`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/994)

Fix typo. It must be rails generate

---

.gitignore
CHANGELOG.md
lib/generators/react_on_rails/react_with_redux_generator.rb

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1019)

Fix redux generator

---

lib/react_on_rails/version_checker.rb

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1039)

Update version_checker.rb for new rubocop.

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1052)

Adding `bundle install` step to basic installation

---

CHANGELOG.md
docs/basics/upgrading-react-on-rails.md
lib/react_on_rails/react_on_rails_helper.rb
spec/dummy/spec/features/rails_context_spec.rb

Per https://github.com/shakacode/react_on_rails/issues/697
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1065)

Added railsEnv to the default railsContext

---

react_on_rails.gemspec
spec/dummy/Gemfile
spec/dummy/Gemfile.lock
spec/dummy_no_webpacker/Gemfile
spec/dummy_no_webpacker/Gemfile.lock
spec/dummy_no_webpacker/Gemfile.rails32
spec/dummy_no_webpacker/Gemfile.rails32.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1080)

Update rainbow gem

---

CHANGELOG.md
lib/react_on_rails/prerender_error.rb
spec/react_on_rails/prender_error_spec.rb

* Create a hash for Sentry (Raven) and Honeybadger for prerender errors
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1081)

Refined error reporting

---

spec/dummy/Gemfile.lock
spec/dummy/spec/helpers/react_on_rails_helper_spec.rb
spec/dummy/spec/rails_helper.rb
spec/dummy/spec/support/driver_registration.rb
spec/dummy/spec/system/integration_spec.rb
spec/dummy/spec/system/rails_context_spec.rb
spec/dummy_no_webpacker/spec/rails_helper.rb

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1088)

Switch to system specs and headless chrome as default driver

---

lib/react_on_rails.rb
lib/react_on_rails/json_parse_error.rb
lib/react_on_rails/prerender_error.rb
lib/react_on_rails/react_component/render_options.rb
lib/react_on_rails/server_rendering_pool/ruby_embedded_java_script.rb
spec/dummy/app/controllers/application_controller.rb
spec/dummy/spec/requests/server_render_check_spec.rb
spec/dummy_no_webpacker/client/package.json
spec/dummy_no_webpacker/client/yarn.lock
spec/dummy_no_webpacker/config/environments/test.rb

Provide the context of what JSON was received to Honeybadger and Raven
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1086)

Accurately track any JSON Parser errors

---

package.json
spec/dummy/Gemfile.lock
spec/dummy/client/package.json
spec/dummy/client/yarn.lock
spec/dummy_no_webpacker/Gemfile.lock
spec/dummy_no_webpacker/client/package.json
spec/dummy_no_webpacker/client/yarn.lock

Per npm docs.
* https://stackoverflow.com/questions/44037774/best-practice-for-upgrading-npm-prepublish-script-for-npm-4/44136814?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa
* https://github.com/npm/npm/issues/16685
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1090)

Change prepublish to prepare

---

CHANGELOG.md
docs/additional-reading/rspec-configuration.md
docs/basics/configuration.md
docs/basics/upgrading-react-on-rails.md
lib/react_on_rails/configuration.rb
lib/react_on_rails/prerender_error.rb
lib/react_on_rails/version_syntax_converter.rb
rakelib/release.rake
spec/dummy/client/webpack.client.rails.build.config.js
spec/react_on_rails/configuration_spec.rb
spec/react_on_rails/generators/version_syntax_converter_spec.rb

Misc doc updates and other cleanups.
Review comments are in #1093.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1101)

Cleanup of configuration object

---

lib/generators/react_on_rails/base_generator.rb

Fix broken link.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1106)

Fix broken link in base generator

---

lib/generators/react_on_rails/base_generator.rb

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1109)

Fix typo on base_generator.rb

---

.rubocop.yml
docs/api/view-helpers-api.md
docs/basics/react-server-rendering.md
react_on_rails.gemspec
spec/dummy/Gemfile.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1113)

Doc changes

---

lib/react_on_rails/configuration.rb

Probably a typo.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1123)

Fix invalid logger warn

---

spec/dummy/spec/helpers/react_on_rails_helper_spec.rb

- Updates dummy deps
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1130)

Adds test for `json_safe_and_pretty` for avoiding regressions

---

.rubocop.yml
CHANGELOG.md
lib/generators/react_on_rails/dev_tests_generator.rb
lib/react_on_rails/react_component/render_options.rb
lib/react_on_rails/utils.rb
spec/dummy/Gemfile.lock
spec/dummy/spec/helpers/react_on_rails_helper_spec.rb
spec/react_on_rails/react_component/render_options_spec.rb
spec/react_on_rails/utils_spec.rb

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1132)

Updated rubocop to 0.58.2

---

COMM-LICENSE

Based on SideKiq Pro
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1143)

Added commercial license

---

README.md
docs/basics/client-vs-server-rendering.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1149)

Server Rendering Tips

---

spec/dummy_no_webpacker/Gemfile.lock
spec/dummy_no_webpacker/client/package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1180)

Update gem and package version

---

README.md
docs/testimonials/resortpass.md
docs/testimonials/testimonials.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1179)

Add testimonials

---

.travis.yml
CHANGELOG.md
docs/api/view-helpers-api.md
lib/react_on_rails/helper.rb

* No longer private
* default value for server_side is true
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1183)

Easier to use rails_context helper

---

README.md
SUMMARY.md
docs/basics/minitest-configuration.md
docs/basics/rspec-configuration.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1188)

Update docs for minitest

---

.travis.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1189)

Test against Ruby 2.6.0 on Travis CI

---

CHANGELOG.md
docs/api/view-helpers-api.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1212)

Update CHANGELOG.md and docs

---

docs/basics/installation-into-an-existing-rails-app.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1232)

Fixed a typo in installation doc for an existing rails app.

---

docs/additional-reading/react-router.md

**1. update react-router.md for react router v4**
1.1 update client-side router docs
1.2 update server-side router docs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1218)

Applying for the Full Stack Developer

---

.rubocop.yml
lib/generators/react_on_rails/generator_helper.rb
lib/react_on_rails/error.rb
lib/react_on_rails/helper.rb
lib/react_on_rails/json_parse_error.rb
lib/react_on_rails/prerender_error.rb
lib/react_on_rails/server_rendering_pool/ruby_embedded_java_script.rb
lib/react_on_rails/test_helper/ensure_assets_compiled.rb
lib/react_on_rails/utils.rb
lib/react_on_rails/version.rb
lib/react_on_rails/webpacker_utils.rb
react_on_rails.gemspec
spec/dummy/Gemfile
spec/dummy/Gemfile.lock
spec/dummy/config/initializers/listen.rb
spec/dummy/spec/rails_helper.rb
spec/dummy/spec/requests/console_logging_spec.rb
spec/dummy/spec/support/selenium_logger.rb
spec/react_on_rails/support/generator_spec_helper.rb
spec/react_on_rails/test_helper/webpack_assets_compiler_spec.rb

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1258)

rubocop fixes

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1270)

Add a heroimage and buttons to README.md

---

node_package/src/ComponentRegistry.ts
node_package/src/clientStartup.ts
node_package/src/createReactOutput.ts
package-scripts.yml
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1279)

Some TS linting

---

package.json
yarn.lock

Fix https://github.com/shakacode/react_on_rails/issues/1278
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1281)

Update core js

---

CONTRIBUTING.md
react_on_rails.gemspec
spec/dummy/Gemfile
spec/dummy/Gemfile.lock
spec/react_on_rails/test_helper/webpack_assets_compiler_spec.rb

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1288)

Update Rubocopcop to 0.85.0 and lock version

---

CHANGELOG.md
docs/outdated/how-react-on-rails-works.md
docs/tutorial.md
lib/generators/react_on_rails/base_generator.rb
lib/generators/react_on_rails/templates/base/base/Procfile.dev
lib/generators/react_on_rails/templates/base/base/Procfile.dev-hmr
lib/generators/react_on_rails/templates/base/base/Procfile.dev-server
lib/generators/react_on_rails/templates/base/base/app/javascript/bundles/HelloWorld/components/HelloWorld.jsx
spec/dummy/Procfile
spec/dummy/Procfile.dev-hmr
spec/dummy/Procfile.dev.no.turbolinks
spec/dummy/Procfile.static
spec/dummy/Procfile.static.no.turbolinks
spec/dummy/README.md
spec/dummy/config/webpack/development.js
spec/dummy/config/webpack/server.js
spec/react_on_rails/support/shared_examples/base_generator_examples.rb

* Using React Hooks
* Changed names of Proc file to Procfile.dev-hmr
* Misc doc updates
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1295)

Updated Generator Files

---

lib/tasks/assets.rake
node_package/src/createReactOutput.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1302)

do not run bin webpack if react on rails handling

---

.rubocop.yml
docs/additional-reading/converting-from-custom-webpack-config-to-rails-webpacker-config.md
docs/additional-reading/server-rendering-tips.md
lib/tasks/assets.rake
rakelib/examples.rake
rakelib/lint.rake
rakelib/release.rake

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1305)

Misc doc and lint updates

---

lib/tasks/assets.rake

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1306)

Fix webpacker clean issue

---

README.md
docs/tutorial.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1314)

Update README.md and tutorial.md

---

CHANGELOG.md
node_package/src/ReactOnRails.ts
node_package/src/StoreRegistry.ts
node_package/src/types/index.ts

Fixes #1321
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1323)

Remove dependency upon Redux for types

---

docs/basics/hmr-and-hot-reloading-with-the-webpack-dev-server.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1322)

Update HMR instructions

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1333)

Update README.md and other docs

---

README.md
docs/tutorial.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1337)

React Hooks Message

---

docs/additional-details/generator-details.md
docs/additional-details/manual-installation-overview.md
docs/api/view-helpers-api.md
docs/contributor-info/linters.md
docs/contributor-info/pull-requests.md
docs/guides/client-vs-server-rendering.md
docs/guides/deployment.md
docs/guides/getting-started.md
docs/guides/how-react-on-rails-works.md
docs/guides/how-to-conditionally-server-render-based-on-device-type.md
docs/guides/installation-into-an-existing-rails-app.md
docs/guides/rails-webpacker-react-integration-options.md
docs/guides/react-on-rails-overview.md
docs/guides/react-server-rendering.md
docs/guides/rspec-configuration.md
docs/guides/tutorial.md
docs/guides/upgrading-react-on-rails.md
docs/guides/webpack-configuration.md
docs/home.md
docs/javascript/code-splitting.md
docs/misc/articles.md
docs/misc/doctrine.md
docs/outdated/rails-assets-relative-paths.md
docs/outdated/rails-assets.md
docs/rails/convert-rails-5-api-only-app.md
docs/react-on-rails-pro/react-on-rails-pro.md
docs/testimonials/testimonials.md

Add trailing slashes to prevent 301 redirects.
Related PR https://github.com/shakacode/sc-website/pull/174
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1384)

Update links to shakacode.com docs

---

CHANGELOG.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1389)

Update changelog for 12.4.0

---

lib/react_on_rails/helper.rb
lib/react_on_rails/server_rendering_js_code.rb

Fix issue #1397
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1401)

Display error message when no config.server_bundle_js_file is provided

---

CHANGELOG.md
lib/react_on_rails/server_rendering_pool/ruby_embedded_java_script.rb

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1412)

Check for "include_execjs_polyfills" method before calling it

---

.circleci/config.yml
.github/workflows/main.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1414)

lock platform for bundler

---

CHANGELOG.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1426)

Add changelog entry for RenderingPropsExtension

---

.circleci/config.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1422)

Give spec/dummy bundle job proper prerequisites

---

CHANGELOG.md
lib/generators/react_on_rails/base_generator.rb
lib/generators/react_on_rails/templates/base/base/config/webpack/development.js.tt
lib/generators/react_on_rails/templates/base/base/config/webpack/production.js.tt
lib/generators/react_on_rails/templates/base/base/config/webpack/test.js.tt
lib/generators/react_on_rails/templates/base/base/config/webpack/webpack.config.js.tt
lib/react_on_rails/helper.rb
lib/react_on_rails/json_parse_error.rb
lib/react_on_rails/prerender_error.rb
lib/react_on_rails/server_rendering_pool/ruby_embedded_java_script.rb

* Also fixed incorrect error handling
Addresses #1429
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1430)

Fixed generator to support Shakapacker

---

CHANGELOG.md
NEWS.md
README.md
docs/additional-details/recommended-project-structure.md
docs/guides/rails-webpacker-react-integration-options.md
docs/guides/react-server-rendering.md
docs/guides/tutorial.md
docs/guides/webpack-configuration.md
docs/home.md
lib/generators/react_on_rails/templates/base/base/babel.config.js.tt
lib/generators/react_on_rails/templates/base/base/config/webpack/clientWebpackConfig.js.tt
lib/generators/react_on_rails/templates/base/base/config/webpack/commonWebpackConfig.js.tt
lib/generators/react_on_rails/templates/base/base/config/webpack/development.js.tt
lib/generators/react_on_rails/templates/base/base/config/webpack/production.js.tt
lib/generators/react_on_rails/templates/base/base/config/webpack/serverWebpackConfig.js.tt
lib/generators/react_on_rails/templates/base/base/config/webpack/test.js.tt
lib/generators/react_on_rails/templates/base/base/config/webpack/webpackConfig.js.tt

Match the tutorial
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1431)

Change the test generated webpack file

---

README.md

fix link from
to
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1434)

Fix webpacker link in README.md

---

CHANGELOG.md
node_package/src/supportsReactCreateRoot.js
node_package/src/supportsReactCreateRoot.ts
node_package/tests/supportsReactCreateRoot.test.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1435)

react 16 doesn't support version property

---

docs/home.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1446)

Update getting started doc link

---

Gemfile.development_dependencies
docs/guides/tutorial.md
spec/dummy/Gemfile.lock
spec/dummy/package.json
spec/dummy/yarn.lock

This should fix CI!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1456)

update to shakapacker 6.4.0

---

docs/guides/client-vs-server-rendering.md
docs/guides/configuration.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1462)

mini_racer documentation note

---

docs/getting-started.md
docs/guides/tutorial.md

resolve #1447
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1461)

Update Tutorial docs with setting ENV variables section

---

CHANGELOG.md
lib/react_on_rails/server_rendering_pool/ruby_embedded_java_script.rb

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1473)

Remove include_execjs_polyfills logic

---

docs/getting-started.md

Fix for #1488 .
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1494)

Minor doc update to address #1488

---

README.md

Brought "The following companies support..." above the logos.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1500)

Bring the text above the images

---

lib/react_on_rails/helper.rb
lib/react_on_rails/packs_generator.rb
spec/react_on_rails/packs_generator_spec.rb

Fixing a misspelled word.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1504)

enteries => entries

---

docs/guides/deployment.md
docs/guides/file-system-based-automated-bundle-generation.md
docs/guides/how-react-on-rails-works.md
docs/guides/how-to-conditionally-server-render-based-on-device-type.md
docs/guides/installation-into-an-existing-rails-app.md
docs/guides/tutorial.md

- Update outdated instructions
- Improve structure
- Update Ruby, node, and gems' versions
Note:
Several files are outdated and I am not sure if they are still relevant at all. We need to check the entire documentation for such content and possibly restructure some parts (like Heroku deployment or HMR).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1517)

Update outdated instructions in documentations

---

lib/generators/react_on_rails/bin/dev
lib/generators/react_on_rails/bin/dev-static
lib/generators/react_on_rails/install_generator.rb
spec/react_on_rails/binstubs/dev_spec.rb
spec/react_on_rails/binstubs/dev_static_spec.rb

In this PR I have fixed two issues:
- The scripts were not able to run the task runner properly.
- The executable flag of the scripts were not preserved in the installation process.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1519)

Fix bin dev scripts

---

Gemfile.development_dependencies
lib/react_on_rails/helper.rb
spec/dummy/spec/support/selenium_logger.rb

Changes required for https://github.com/shakacode/react_on_rails_pro/pull/306
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1518)

Changes required for RoR Pro caching

---

CHANGELOG.md

I forgot to add the entry for bugfix in #1519.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1521)

Add missing entry in changelog for PR1519

---

.github/PULL_REQUEST_TEMPLATE.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1522)

Add PR template for GitHub

---

lib/generators/react_on_rails/bin/dev
lib/generators/react_on_rails/bin/dev-static
spec/react_on_rails/binstubs/dev_spec.rb
spec/react_on_rails/binstubs/dev_static_spec.rb

Fix grammar issue in binstubs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1529)

Fix grammar issue

---

CHANGELOG.md
lib/generators/react_on_rails/templates/base/base/Procfile.dev

Remove useless HMR=true from Procfile
This PR is made based on the discussion with @justin808 on react_on_rails_demo_ssr_hmr upgrade.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1537)

Remove useless HMR=true from Procfile

---

docs/home.md

closes #1556 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1561)

Update outdated link in the docs (#1556)

---

CHANGELOG.md

- Updated all release dates for ROR 13.3.x from 2022 to 2023
- Fix heading levels to follow the format of the document
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1557)

Fix issues in Changelog

---

.circleci/config.yml
.github/workflows/lint-js-and-ruby.yml
.github/workflows/main.yml
.github/workflows/rspec-package-specs.yml
Gemfile.development_dependencies
spec/dummy/Gemfile.lock

As per Justin's request.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1564)

Upgrade bundler to 2.4.17

---

docs/guides/file-system-based-automated-bundle-generation.md

Minor update in the formatting of the docs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1569)

Update format improvement

---

lib/generators/react_on_rails/templates/base/base/config/shakapacker.yml

A minor typo fix in a comment of the shakapacker.yml file.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1576)

Fix typo in shakapacker.yml related to Procfile.dev-static

---

docs/additional-details/migrating-from-react-rails.md

Update documentation related to migration from `react-rails.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1577)

Update docs for migrating from react-rails

---

CHANGELOG.md

Updating changelog for #1582 so we can make a new minor release for the type fixes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1584)

Update changelog for #1582

---

.gitignore
spec/dummy/.gitignore

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1599)

Improve .gitignore file

---

CHANGELOG.md
react_on_rails.gemspec
spec/dummy/config/initializers/content_security_policy.rb
spec/dummy/config/initializers/inflections.rb
spec/dummy/config/initializers/permissions_policy.rb
spec/dummy/db/seeds.rb

Update filter for included gem files
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1605)

trim gem files

---

yarn.lock

Updated JS dependencies for security fixes
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1604)

Fix JS vulnerabilities in dev dependencies

---

Gemfile.lock

_Remove this paragraph and provide a general description of the code changes in your pull
request... were there any bugs you had fixed? If so, mention them. If
these bugs have open GitHub issues, be sure to tag them here as well,
to keep the conversation linked together._
_Add the CHANGELOG entry at the top of the file._
_Remove this paragraph and mention any other important and relevant information such as benchmarks._
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1755)

Update react_on_rails to version 15.0.0.rc.2 in Gemfile.lock
