spec/dummy/Gemfile, spec/dummy/Gemfile.lock
Update gem uglifier to >= 2.7.2 to address security alert for affected
versions prior to 2.7.2
Sources: https://github.com/lautis/uglifier/pull/86
https://zyan.scripts.mit.edu/blog/backdooring-js/
https://nodesecurity.io/advisories/uglifyjs_incorrectly_handles_non-boolean_comparisons
https://github.com/mishoo/UglifyJS2/issues/751
=> Address security alert for gem uglifier

app/helpers/react_on_rails_helper.rb, lib/react_on_rails/react_renderer.rb, spec/dummy/app/views/pages/_header.erb, spec/dummy/app/views/pages/server_side_log_throw.html.erb, spec/dummy/client/app/components/HelloWorldWithLogAndThrow.jsx, spec/dummy/client/app/startup/clientGlobals.jsx, spec/dummy/client/app/startup/serverGlobals.jsx, spec/dummy/config/routes.rb, spec/dummy/spec/sample_generated_js/client-generated.js, spec/dummy/spec/sample_generated_js/server-generated.js
This should fix #36.
@justin808 Can you review it?
=> Fix bug in error messages printing

README.md, app/helpers/react_on_rails_helper.rb, lib/react_on_rails/configuration.rb, lib/react_on_rails/react_renderer.rb, spec/dummy/Gemfile.lock, spec/dummy/app/views/pages/_header.erb, spec/dummy/app/views/pages/server_side_hello_world_with_options.html.erb, spec/dummy/config/initializers/react_on_rails.rb, spec/dummy/config/routes.rb
* Options passed through to content tag
* Now you can have replay_console set to false and logging_server_set to
true and server messages go only to the server. replay_console only
affects the browser console display.
=> Pass options to content tag

README.md, spec/dummy/client/app/startup/serverGlobals.jsx, spec/dummy/client/webpack.server.js
We did not need to specify libraryTarget if using global.MyComponent
rather than the expose syntax for server rendering.
=> Updated docs for libraryTarget info

.simplecov, Rakefile, docs/Contributing.md, spec/dummy/spec/rails_helper.rb, spec/empty_spec.rb, spec/react_on_rails_spec.rb, spec/spec_helper.rb
- switch from Coveralls `wear_merged!` to SimpleCov in order to specify the correct output coverage folder
- employ `TEST_ENV_NUMBER` environment variables in rake task to ensure dummy apps are uniquely named via `SimpleCov.command_name`
- add `.simplecov` file to start the coverage process and avoid covering anything that doesn't have `COVERAGE=true` environment variable (prevents error messages when running "coveralls:push"
- employ `COVERAGE=true` environment variables in rake tasks
- use `run_rspec:empty` rake task on `empty_spec.rb` to compel SimpleCov to generate a new, all-inclusive report after running tests
- update `docs/Contributing.md` to include information on how to view a coverage report locally
=> Fix coverage to include dummy app specs

.travis.yml, Dockerfile_ci
Set travis.yml for running `rake` natively  with Xvfb headless browser testing with selenium_firefox.
This will allow proper code coverage reporting to the Coveralls API from travis-ci builds.
Set linting  within the build from docker-lint container.
Remove docker-ci build from travis.ymi since docker-ci is not configured to report Coveralls properly from travis.
=> Docker ci coveralls reporting

Rakefile
this has been driving me nuts! It causes the CI to fail if you don't successfully get through the linters, and I forget to run it after `rake` all the time!
=> Make default rake task run docker:lint

lib/generators/react_on_rails/templates/base/base/config/initializers/react_on_rails.rb
this was missed due to the timing of making the variable name change w/ the generators branch in flight etc etc.
=> fixes the variable name change

lib/generators/react_on_rails/templates/linters/client/.eslintrc
otherwise post-generation the eslintrc will flag the import _ from 'lodash'; lines in the components as bad.
=> lodash / _ has to be excluded from the minimum 2 rule.

lib/generators/react_on_rails/bootstrap_generator.rb, lib/generators/react_on_rails/generator_helper.rb, spec/react_on_rails/generators/install_generator_spec.rb, spec/react_on_rails/support/generator_spec_helper.rb, spec/react_on_rails/support/shared_examples/bootstrap_generator_examples.rb
Makes the generator recognize `application.scss` files instead of only looking for `application.css.scss` by just forcing all variations to be `application.scss`.
Fixes #86
We're just forcing any version of application.css or
application.css.scss to be application.scss
This avoids a lot of headache when trying to reference the file
in multiple places, and ensures that users could have either variation without the generator failing.
=> Make generator recognize application.scss

app/assets/javascripts/react_on_rails.js, app/helpers/react_on_rails_helper.rb, spec/dummy/spec/requests/console_logging_spec.rb
Props is passed to component, so no need for the globally exposed props.
This was probably some artifact of an earlier iteration.
=> Removed unnecessary global exposed window variable

app/assets/javascripts/react_on_rails.js, app/helpers/react_on_rails_helper.rb, spec/dummy/spec/helpers/react_on_rails_helper_spec.rb, spec/dummy/spec/requests/console_logging_spec.rb
=> Use data attrs when rendering react_components instead of script tags

.eslintignore, .eslintrc, .jscsrc, lib/generators/react_on_rails/templates/base/base/lib/tasks/linters.rake.tt, lib/generators/react_on_rails/templates/js_linters/client/.eslintrc, lib/generators/react_on_rails/templates/js_linters/client/.jscsrc, lib/generators/react_on_rails/templates/no_redux/base/client/app/bundles/HelloWorld/components/HelloWorldWidget.jsx, lib/generators/react_on_rails/templates/redux/base/client/app/lib/middlewares/loggerMiddleware.js
This change is in parallel with the change made for the webpack
tutorial.
See https://github.com/shakacode/react-webpack-rails-tutorial/pull/159
=> Update linters to conform to ShakaCode standards

lib/generators/react_on_rails/base_generator.rb, spec/react_on_rails/generators/install_generator_spec.rb, spec/react_on_rails/support/generator_spec_helper.rb, spec/react_on_rails/support/shared_examples/base_generator_examples.rb
Fixes #78
Generator used to put a setup error message when it did not find
application.js. Now, it will simply just create one with the
necessary data in it.
=> Have generator create application.js file if not found

lib/generators/react_on_rails/templates/base/base/client/webpack.client.base.config.js.tt, lib/generators/react_on_rails/templates/base/base/client/webpack.client.rails.config.js
when trying to run `foreman start -f Procfile.dev`, I was getting the error - 
`ReferenceError: NODE_ENV is not defined`
Then when I checked in webpack.server.rails.config.js I noticed that the variable `NODE_ENV` was indeed not defined, though a variable `nodeEnv` was. My guess is that `NODE_ENV` and `nodeEnv` are intended to mean the same thing, so I rewrote `NODE_ENV` to `nodeEnv` so they match up. After doing this, I no longer received the `ReferenceError` when running `foreman`.
=> rewrite NODE_ENV as nodeEnv so the two mentions of the variable match up

lib/generators/react_on_rails/bootstrap_generator.rb, spec/react_on_rails/generators/install_generator_spec.rb, spec/react_on_rails/support/generator_spec_helper.rb
First of all thanks for an awesome gem :star: 
react_on_rails:install fails when there is no existing assets initializer file:
```
$ rails generate react_on_rails:install
```
I added a small patch that followed the same pattern used in [`BootstrapGenerator#prepend_to_application_scss `](https://github.com/shakacode/react_on_rails/blob/213fd8049840387f32bdb626e20fbde29a5acea5/lib/generators/react_on_rails/bootstrap_generator.rb#L82).
=> Check for config/initializers/assets.rb file

README.md, lib/generators/react_on_rails/base_generator.rb, lib/generators/react_on_rails/bootstrap_generator.rb, lib/generators/react_on_rails/install_generator.rb, lib/generators/react_on_rails/templates/base/base/client/package.json.tt, lib/generators/react_on_rails/templates/base/base/client/webpack.client.hot.config.js.tt, rakelib/examples_config.yml, spec/react_on_rails/generators/install_generator_spec.rb, spec/react_on_rails/support/shared_examples/base_generator_examples.rb, spec/react_on_rails/support/shared_examples/bootstrap_generator_examples.rb
Really busy in whole last week, only start to have some time for #96  
It's not fully ready yet. But I hope to have this PR submitted for people to review and give me feedback, so that I am able to make it better. I still need to adjust/add some rspec testings.
=> Bootstrap as an option for generator

docs/additional_reading/react_router.md
I had some trouble getting react-router to work, though after @justin808 pointed me to the tutorial code I was able to figure it out. Think it might be useful for others to see a mention of the tutorial code in the react-router docs.
=> mention tutorial code in docs related to react-router integration

lib/generators/react_on_rails/templates/base/base/client/package.json.tt
It seems like we need `lodash` even for version without redux
https://github.com/shakacode/react_on_rails/blob/master/lib/generators/react_on_rails/templates/no_redux/base/client/app/bundles/HelloWorld/components/HelloWorldWidget.jsx#L2
Relate to #162
=> Lodash to default dependencies

lib/generators/react_on_rails/templates/base/base/client/webpack.client.base.config.js.tt, lib/generators/react_on_rails/templates/base/base/client/webpack.client.rails.config.js
@justin808 - Do I misunderstand your purpose of issue #169 ?
=> remove jquery_ujs dependency to fix #169

lib/generators/react_on_rails/base_generator.rb, lib/generators/react_on_rails/bootstrap_generator.rb, lib/generators/react_on_rails/generator_errors.rb, lib/generators/react_on_rails/generator_helper.rb, lib/generators/react_on_rails/install_generator.rb, spec/react_on_rails/generators/install_generator_spec.rb, spec/react_on_rails/support/generator_spec_helper.rb, spec/react_on_rails/support/shared_examples/generator_errors_examples.rb
Added an ‘errors’ attribute to the install generator class which gets passed, as an option, to the generators that output errors.
Errors outputted get pushed into the errors attr array. At the end of the install any errors in the attr array get printed to the terminal.
=> Fixes Generator Warning Messages #138

lib/generators/react_on_rails/bootstrap_generator.rb
Removed the File.exists? check for application.scss because it gets created if it doesn’t exist in the method before it.
(cc @robwise)
=> Fix #189 Generator Error for application.scss

lib/generators/react_on_rails/generator_messages.rb, lib/generators/react_on_rails/install_generator.rb, spec/react_on_rails/generators/generator_messages_spec.rb
Updated the 'errors' wording used in GeneratorMessages to 'messages' because this singleton is also outputting warning and info messages.
=> Clarify Generator Messages

README.md, lib/generators/react_on_rails/templates/base/base/client/package.json.tt, lib/react_on_rails/version_checker.rb, lib/react_on_rails/version_syntax_converter.rb, spec/react_on_rails/generators/install_generator_spec.rb, spec/react_on_rails/generators/version_syntax_converter_spec.rb, spec/react_on_rails/support/version_test_helpers.rb, spec/react_on_rails/version_checker_spec.rb
Also makes some fixes to the README.
This improves the recent hotfix so that we can match against all types of gem versions, including `beta` or `rc` suffixed ones.
=> Improve package json template

docs/tutorial-v2.md, lib/generators/react_on_rails/base_generator.rb, lib/generators/react_on_rails/react_with_redux_generator.rb, lib/generators/react_on_rails/templates/base/base/package.json, spec/react_on_rails/generators/install_generator_spec.rb
- Added a helpful message after base generator install.
- Added a helpful message after react with redux generator install.
- Added tests for both messages.
`rails generate react_on_rails:install`
`rails generate react_on_rails:install -R`
Resloves #184
=> Helpful Message After Generator Install

README.md, docs/additional_reading/rspec_configuration.md, lib/react_on_rails.rb, lib/react_on_rails/ensure_assets_compiled.rb, spec/dummy/client/package.json, spec/dummy/package.json, spec/dummy/spec/rails_helper.rb
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/222)
=> Add EnsureAssetsCompiled feature

lib/generators/react_on_rails/generator_messages.rb, react_on_rails.gemspec
In one of my previous PR's we had to do a 'hacky' fix to get X11 colors to output with the GeneratorMessages. https://github.com/shakacode/react_on_rails/pull/217
I was able to fix the problem with the rainbow gem and get a PR merged: https://github.com/sickill/rainbow/issues/27. The author updated the version of the gem to 2.1.0.
- New version of rainbow fixes bug with X11 colors.
- Use ‘orange’ instead of RGB color.
=> Bump rainbow gem version to >= 2.1.0.

lib/react_on_rails.rb, lib/react_on_rails/engine.rb, lib/react_on_rails/version_checker.rb
Put require statements all in one place. This will address an issue 
where the user is warned that React on Rails
is attempting to set a constant twice. This was happening because
the version.rb file was being required from multiple locations.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/226)
=> Fix requires

rakelib/example_type.rb, spec/dummy/Gemfile.lock
For some reason, dynamically defining methods doesn't get evaluated when doing `rake -T`, so we have to define them explicitly.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/229)
=> Fix rake task names

README.md, docs/coding-style/style.md, docs/doctrine.md, docs/recommended-project-structure.md
First drafts of
* The React on Rails Doctrine
* Recommended Project Structure
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/220)
=> The React On Rails Doctrine

README.md, docs/additional_reading/rails_view_rendering_from_inline_javascript.md, node_package/src/ReactOnRails.js, node_package/tests/ReactOnRails.test.js, package.json
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/234)
=> Make ReactOnRails.render return a reference to the component's backing instance

CHANGELOG.md, app/assets/javascripts/debug_turbolinks.js, docs/additional_reading/turbolinks.md, node_package/src/clientStartup.js, rakelib/run_rspec.rake, spec/dummy/Gemfile, spec/dummy/Gemfile.lock, spec/dummy/Procfile.dev.no.turbolinks, spec/dummy/app/assets/javascripts/application.js, spec/dummy/app/assets/javascripts/application_with_turbolinks.js, spec/dummy/app/assets/javascripts/testGlobals.js, spec/dummy/app/views/layouts/application.html.erb, spec/dummy/config/initializers/assets.rb, spec/dummy/spec/helpers/react_on_rails_helper_spec.rb
- React components were not being rendered because of a double
nesting of event handlers when React on Rails did not detect
that Turbolinks was installed. This has been fixed.
- Add `debug_turbolinks` helper file so that the user can simply
require their file in their application.js file to debug turbolinks.
Documentation has been improved to show how to do this.
- Add section to turbolinks troubleshooting documentation recommending
that users use the node package versions of jQuery and jQuery-ujs.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/241)
=> Fix rendering in non-Turbolink apps and improve Turbolink docs

CHANGELOG.md, lib/react_on_rails.rb, lib/react_on_rails/ensure_assets_compiled.rb, lib/react_on_rails/webpack_assets_status_checker.rb, spec/react_on_rails/ensure_assets_compiled_spec.rb, spec/react_on_rails/support/fixtures_helper.rb, spec/react_on_rails/webpack_assets_status_checker_spec.rb
This commit changes the EnsureAssetsCompiled feature that ensures
RSpec tests are run with the latest webpack bundles. Previously,
webpack bundles would be rebuilt every test run, whether or not
they actually needed to be. While one could around this by running
webpack in the background to rebuild the static assets, doing so
required users to name their webpack build script exactly correct
as the technique relied on a `pgrep`.
Instead, the functionality checks the mdate on each generated webpack
bundle/asset against the mdate of every file inside of the `client`
directory, which is all encapsulated by the standard library method
`FileUtils.uptodate?` and is very performant. This eliminates the
need to check for an existing webpack process because the webpack
bundles will be up to date …
=> Optimize efficiency of EnsureAssetsCompiled functionality

lib/generators/react_on_rails/bootstrap_generator.rb
Fixes #256 
If the gemfile does not have an empty line at the end, append_to_file will append ‘gem bootstrap-sass’ to the last line.
- Added a line break to the beginning of ‘gem bootstrap-sass’ to ensure it’s on a new line.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/262)
=> Fix Bootstrap Sass Append to Gemfile

.travis.yml, Gemfile, docs/additional_reading/turbolinks.md, docs/contributing.md, node_package/src/clientStartup.js, rakelib/dummy_apps.rake, rakelib/run_rspec.rake, rakelib/task_helpers.rb, spec/dummy/Gemfile, spec/dummy/Gemfile.lock
- Add version check by using feature detection.
- Update dummy app to use Turbolinks 5
***
Alternate method to #264
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/270)
=> Add Turbolinks 5 Support Version Check

lib/generators/react_on_rails/base_generator.rb, lib/generators/react_on_rails/templates/base/base/config/initializers/react_on_rails.rb.tt, spec/react_on_rails/support/shared_examples/base_generator_examples.rb
- Change react_on_rails.rb to a thor template
- Added server_rendering conditional
- Added comment
- Added tests
***
Fixes #294
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/295)
=> Fix config.server_bundle_js file in generator

lib/generators/react_on_rails/templates/base/base/client/server.js, lib/generators/react_on_rails/templates/base/base/lib/tasks/linters.rake.tt
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/299)
=> prevent concatenation of rake lint params to npm lint params

CHANGELOG.md, README.md, node_package/src/StoreRegistry.js, node_package/tests/StoreRegistry.test.js
Better registered errors when store cannot be found.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/301)
=> Update StoreRegistry.js missing store error.

docs/additional_reading/heroku_deployment.md
Was just reading through the docs about setting up the recommended buildpack, and felt like the existing multiple buildpack link was not really an alternative approach. It contains the same approach specified above, but also some extra information.
A little picky, maybe, but I thought it might clarify things a bit and it gives me the opportunity for my first contribution :tada:
Thoughts?
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/306)
=> Clarify multi-buildpack link and strip whitespace

lib/react_on_rails/git_utils.rb
When I tried to install react_on_rails, I got "ERROR: You have uncommitted code. Please commit or stash your changes before continuing." but all of my code were committed. 
The problem was in the git localization: "нечего фиксировать, рабочая директория пуста" instead of "nothing to commit, working directory clean" (but both are the same).
Here is the fix that checks on empty git status if no uncommitted changes.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/303)
=> Fix uncommitted code error.

package.json
Starting with a freshly installed copy of this project's repo, `npm run build` fails trying to install `babel` as the package no longer exists (see http://jamesknelson.com/the-six-things-you-need-to-know-about-babel-6/). Removing it solves the problem.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/321)
=> Remove the babel package from the devDependencies

docs/additional_reading/heroku_deployment.md, docs/tutorial-v2.md, lib/generators/react_on_rails/heroku_deployment_generator.rb, lib/generators/react_on_rails/templates/heroku_deployment/.buildpacks, spec/react_on_rails/support/shared_examples/heroku_deployment_generator_examples.rb
I was trying to use `heroku-buildpack-multi` and was getting failures when trying to push to Heroku. This led me to realize that Heroku natively supports using multiple build packs now, so there is no need to use `heroku-buildpack-multi` or have to worry about a `.buildpack` file. I simplified the instructions and removed references to `.buildpack` in the code. Now, all you have to worry about is running this from the CLI:
```
heroku buildpacks:set heroku/ruby
heroku buildpacks:add --index 1 heroku/nodejs
```
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/319)
=> Remove use of heroku-buildpack-multi

CHANGELOG.md, NEWS.md, README.md, lib/react_on_rails/controller.rb, spec/dummy/Gemfile.lock, spec/dummy/app/controllers/pages_controller.rb, spec/dummy/app/views/pages/client_side_hello_world_shared_store.html.erb, spec/dummy/app/views/pages/client_side_hello_world_shared_store_controller.html.erb, spec/dummy/app/views/pages/client_side_hello_world_shared_store_defer.html.erb, spec/dummy/app/views/pages/server_side_hello_world_shared_store.html.erb, spec/dummy/app/views/pages/server_side_hello_world_shared_store_controller.html.erb, spec/dummy/app/views/pages/server_side_hello_world_shared_store_defer.html.erb
2nd parameter of props with default value of { } is changed to a named
parameter props with a default value of { }
Needed for consistency with the view helper redux_store API.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/335)
=> Changed ReactOnRails::Controller#redux_store API

README.md, app/helpers/react_on_rails_helper.rb, docs/additional-reading/react-router.md, lib/react_on_rails/configuration.rb, node_package/src/clientStartup.js, node_package/src/createReactElement.js, spec/dummy/app/controllers/pages_controller.rb, spec/dummy/client/app/components/HelloWorld.jsx, spec/dummy/client/app/components/HelloWorldContainer.jsx, spec/dummy/client/app/components/HelloWorldRedux.jsx, spec/dummy/client/app/components/RailsContext.jsx, spec/dummy/client/app/reducers/RailsContextReducer.jsx, spec/dummy/client/app/reducers/reducersIndex.jsx, spec/dummy/client/app/startup/ClientReduxApp.jsx, spec/dummy/client/app/startup/ServerReduxApp.jsx, spec/dummy/client/app/startup/ServerRouterApp.jsx, spec/dummy/client/app/store/composeInitialState.js, spec/dummy/client/app/stores/SharedReduxStore.jsx, spec/dummy/client/package.json, spec/dummy/config/initializers/react_on_rails.rb, spec/dummy/spec/features/rails_context_spec.rb, spec/dummy/spec/helpers/react_on_rails_helper_spec.rb, spec/dummy/spec/requests/console_logging_spec.rb, spec/dummy/spec/requests/server_render_check_spec.rb, spec/dummy/spec/support/capybara_utils.rb
As of v4, we provide the location as a second param to component generator functions after props, and **ONLY** on the server rendering. This is not in the current API for store generator functions.
Suppose you want to display a nav bar with the current navigation link highlighted by the URL. When you server render the code, you will need to know the current URL/path if that is what you want your logic to be based on. This could be added to props, or ReactOnRails can add this automatically as another param to the generator function (or maybe an additional object, where we'll consider other additional bits of system info from Rails, like maybe the locale, later).
Suppose you want to server render your react components with a the current Rails locale. We need to pass the I18n.locale to the …
=> Providing rails_context always to generator functions (store and component)

node_package/src/buildConsoleReplay.js, node_package/src/scriptSanitizedVal.js, node_package/tests/buildConsoleReplay.test.js, node_package/tests/scriptSanitizedVal.test.js, spec/dummy/client/app/components/HelloWorldRedux.jsx
* Only happened with server rendering.
* Fix is to escape for closing script tag
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/366)
=> Address failure to sanitize console messages

.rubocop.yml, CHANGELOG.md, README.md, app/helpers/react_on_rails_helper.rb, node_package/src/createReactElement.js, node_package/src/scriptSanitizedVal.js, node_package/tests/buildConsoleReplay.test.js, node_package/tests/scriptSanitizedVal.test.js, spec/dummy/client/app/components/HelloWorldRedux.jsx, spec/dummy/client/app/components/RailsContext.jsx, spec/dummy/spec/features/rails_context_spec.rb, spec/dummy/spec/requests/console_logging_spec.rb
* Some cases missed, per: http://stackoverflow.com/a/23983448/1009332
* Added serverRendering and port to railsContext
* Only logging attributes client side if tracing to avoid overwhelming
server logs. On the client, one can optionally toggle expand the
props. On the server, we stringified, and with a big set of props,
that could be huge.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/370)
=> Completes prior fix 366 for script sanitization

package.json
The npm shrinkwrap didn't do anything here since we had no dependencies besides devDependencies.
Added babel-runtime to the root since it's a peerDepenency.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/399)
=> added babel runtime to root package.json and removed npm-shrinkwrap from root

CHANGELOG.md, docs/additional-reading/rails-assets.md, lib/generators/react_on_rails/templates/base/base/config/initializers/react_on_rails.rb.tt, lib/react_on_rails/configuration.rb, lib/tasks/assets.rake
**Problem**
When client js uses images in render methods, e.g. `<img src='...' />` or in css, e.g. `background-image: url(...)` these assets fails to load. This happens because rails adds digest hashes to filenames when compiling assets. e.g. `img1.jpg` becomes `img1-dbu097452jf2v2.jpg`. When compiling its native css rails transforms all urls and links to work on digested versions, i.e. `background-image: url(img1.jpg)` becomes `background-image: url(img1-dbu097452jf2v2.jpg)`. However this doesn't happen for js and css files compiled by webpack on the client side and assets fail to load
**Solution**
Create symlinks of non-digested versions to digested versions when rails assets compile
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" …
=> Added non-digested version for assets (images, fonts, svg)

CHANGELOG.md, app/helpers/react_on_rails_helper.rb
Hey,
I'm operating a website (https://www.apprentus.com) where we user react_on_rails with prerendering to server content to our users. Currently it's just the homepage, with other pages under development.
I started getting errors that our homepage wasn't loading for some users. Digging deeper I found it's because of the character "\u2028" that was being sent in the props under the "latest classes" section, that features user entered content.
Digging further I found this link:
https://bugs.chromium.org/p/v8/issues/detail?id=1907
... and learned these two are special characters in JS.
Try it out yourself by running this in your browser
```js
eval('console.log("\u2028")')
```
If you change the number to 2027 or 2030 then it works fine.
This PR is a quick fix that solved the problem for me, …
=> \u2028 and \u2029 break rendering

CHANGELOG.md, docs/additional-reading/heroku-deployment.md, lib/generators/react_on_rails/templates/base/base/client/package.json.tt
Without this heroku has to do a full npm install on every deploy - i
guess this could be part of the heroku generators but it seemed like a
lot more work to modify this file there than to just add this option
here.
Change by https://github.com/modosc, manually merged
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/415)
=> Cache client/node_modules during heroku deploys

.eslintrc, CHANGELOG.md, NEWS.md, README.md, docs/additional-reading/turbolinks.md, lib/react_on_rails/version.rb, node_package/src/ReactOnRails.js, node_package/src/clientStartup.js, package.json, spec/dummy/Gemfile.lock
See original PR https://github.com/shakacode/react_on_rails/pull/315.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/417)
=> Expose ReactOnRail.reactOnRailsPageLoaded

lib/tasks/assets.rake
The problem was with [this commit](https://github.com/shakacode/react_on_rails/commit/6286cdd791fc6ed4fad628583600938aa9523902#diff-52cfe83d7f9f1c952a7995dfb0f99341), which moved symlink tasks from after `assets:precompile` hook to before `assets:precompile` hook.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/431)
=> fixed asset pipeline

lib/tasks/assets.rake
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/436)
=> added old rails manifest.json support

.travis.yml
Update Travis CI yaml file to install latest, Chrome stable.
This update fixes the failing tests on `master` due to Selenium throwing a error about Chrome being to old.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/447)
=> Update .travis.yml with latest chrome config

CHANGELOG.md, lib/tasks/assets.rake
The problem with Heroku was that it built the app in a tmp folder and then moved in the release folder. Symlinks were created with absolute path, so this process broke symlinks target. This fix creates relative symlinks instead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/446)
=> Fixed assets symlinking for Heroku

docs/basics/installation-overview.md
Link to Heroku Deployment documentation file is broken in the Installation Overview document
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/457)
=> Fix link to Heroku Deployment documentation

README.md, node_package/src/ReactOnRails.js, node_package/src/StoreRegistry.js, node_package/tests/ReactOnRails.test.js, node_package/tests/StoreRegistry.test.js
We had a major yak shave when figuring out why setting up the store from
a content_for block caused majore issues.
The following doc changes and enhanced error messages will save others
from this pain.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/470)
=> Fixes to avoid yak shave with redux_store

CHANGELOG.md, lib/react_on_rails/version_checker.rb, spec/react_on_rails/version_checker_spec.rb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/491)
=> Add support for single digit version strings, closes #489

CHANGELOG.md, lib/react_on_rails/assets_precompile.rb, spec/react_on_rails/assets_precompile_spec.rb
#510 moved to a branch
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/513)
=> Fixed bug to allow filenames with spaces in assets_precompile.rb

lib/react_on_rails/server_rendering_pool.rb, lib/react_on_rails/utils.rb, spec/dummy/Gemfile.lock
```
lib/react_on_rails/server_rendering_pool.rb:19:7: C: Style/MethodMissing: When using method_missing, define respond_to_missing? and fall back on super.
def method_missing(sym, *args, &block) ...
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/react_on_rails/utils.rb:14:7: C: Style/NumericPredicate: Use $CHILD_STATUS.exitstatus.zero? instead of $CHILD_STATUS.exitstatus == 0.
$CHILD_STATUS.exitstatus == 0
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
--
`TravisCI` fails but it is not connected to this PR.
Maybe I can figure it out where is the offender.
Local `rake` command show all green now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/515)
=> A proposal to update the "rubocop"

.travis.yml
Remove installation of [npm poltergeist package](https://www.npmjs.com/package/poltergeist). It seems a typo.
--
`TravisCI`'s recommended way to run `Xvfb` https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
> Note: Don’t run `xvfb` directly, as it does not handle multiple concurrent instances that way.
--
The [npm config set spin false](https://github.com/emberjs/ember.js/blob/86f65045fddd5fdd09685f39884230474dd2e111/.travis.yml#L14) speeds things a bit up.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/516)
=> Clean up a bit travis.yml

docs/additional-reading/react-router.md
Seems the path is incorrect - from a older version of the generator
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/522)
=> Fixed path on additional-reading documentation

NEWS.md, README.md
I copied sections of our github url, rather than our gitbook url, when predicting the url. My bad.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/535)
=> Fix Gitbook links

README.md
the README instructs the user to install v5 of the the gem, but v6 is already available. When I followed the readme, I was very surprised when I ran npm upgrade and immediately got a new version of the npm package, which made me wonder if I was missing updates in the ruby gem as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/536)
=> update gem version suggested in README

lib/react_on_rails/assets_precompile.rb, spec/react_on_rails/assets_precompile_spec.rb, spec/react_on_rails/spec_helper.rb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/541)
=> Fix symlink regression

CHANGELOG.md, lib/react_on_rails/assets_precompile.rb, spec/react_on_rails/assets_precompile_spec.rb
@justin808 Per https://github.com/shakacode/react_on_rails/issues/564.
This allows `react_on_rails` to parse legacy `manifest.yml` documents to discover digest filenames when symlinking compiled assets.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/566)
=> Make assets precompile symlink task compatible with Rails 3

docs/additional-reading/hot-reloading-rails-development.md
The URL is broken on https://shakacode.gitbooks.io/react-on-rails/content/docs/additional-reading/hot-reloading-rails-development.html since it is looking relatively and not at the repo.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/593)
=> Fix broken URL for gitbooks

docs/additional-reading/heroku-deployment.md
The gem is no longer required in Rails 5.
https://github.com/heroku/rails_12factor#rails-5
https://devcenter.heroku.com/articles/getting-started-with-rails5#heroku-gems
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/609)
=> Update 12factor gem requirement

README.md, docs/additional-reading/rails-engine-integration.md
Thanks to @noahprince22! From https://github.com/shakacode/react_on_rails/issues/562#issuecomment-257891002
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/614)
=> add engine doc

node_package/src/StoreRegistry.js
Hi, 
When I was trying to set up server side rendering, I ran into the ['no hydrated stores' error](https://github.com/shakacode/react_on_rails/blob/master/node_package/src/StoreRegistry.js#L42-L46). After some digging, I realised I hadn't called `redux_store_hydration_data` anywhere in my view. 
This should hopefully make it more clear that rendering `redux_store_hydration_data` is required.
Thanks
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/605)
=> Slight improvement to the 'no hydrated stores' error

CHANGELOG.md, lib/generators/react_on_rails/base_generator.rb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/631)
=> Improve generator post-install help messages

lib/react_on_rails/version_checker.rb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/602)
=> handle error where react-on-rails package entry missing

CHANGELOG.md, app/helpers/react_on_rails_helper.rb, spec/dummy/spec/helpers/react_on_rails_helper_spec.rb
Here's a failing test case that demonstrates #634
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/636)
=> react_component outside of view

CHANGELOG.md, node_package/src/clientStartup.js, spec/dummy/Gemfile, spec/dummy/app/views/layouts/application.html.erb, spec/dummy/app/views/pages/_header.erb, spec/dummy/app/views/pages/turbolinks_cache_disabled.erb, spec/dummy/client/app/components/CacheDisabled.js, spec/dummy/client/app/startup/clientRegistration.jsx, spec/dummy/config/routes.rb
This PR includes a page that renders a component when Turbolinks cache is disabled to test whether the component is really unmounted when the user navigates away from the page. The hook on `turbolinks:before-visit` will ensure that this will happen in all cases. The previous event hook `turbolinks:before-cache` was not called when the Turbolinks cache is disabled with a <meta/> tag. That's why the erb page adds a meta tag to disable the cache.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/644)
=> Use `turbolinks:before-visit`, not `turbolinks:before-cache`

.travis.yml, CHANGELOG.md, app/helpers/react_on_rails_helper.rb, lib/react_on_rails/react_component/options.rb, lib/react_on_rails/test_helper/webpack_assets_status_checker.rb, lib/react_on_rails/utils.rb, react_on_rails.gemspec, spec/dummy/Gemfile, spec/dummy/Gemfile.lock
First of all, let me express how grateful I am for this gem. I've recently been learning about react and webpack, and react_on_rails has made it a breeze to implement what I've learned in my Rails projects! It's allowed us to add "sprinkles" of React in certain Rails views, without commiting to rewriting everything from scratch. Thank you!
Now, for a project I'm currently working on, we need compatibility with Ruby 2.0 (yeah yeah, I know it's not receiving fixes or patches anymore, but we can't upgrade yet.)
The [rubygems page for react_on_rails](https://rubygems.org/gems/react_on_rails) doesn't specify a minimum ruby version, but if you try to use the gem with < 2.1, it breaks because of the required keyword arguments that were introduced in 2.1.
The changes in this PR do "backport" this …
=> Compatibility with Ruby 2.0+

CHANGELOG.md, node_package/src/clientStartup.js
By checking with Turbolinks.supported API, fallback unsupported browser to non Turbolinks mode.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/650)
=> Disable Turbolinks support when not supported

README.md, docs/additional-reading/foreman-issues.md, react_on_rails.gemspec
According https://github.com/ddollar/foreman
> Ruby users should take care not to install foreman in their project's Gemfile.
and known issues with `foreman` I suggest to remove `foreman` from gem dependencies and install it manually.
This PR is related to discussion https://github.com/shakacode/react_on_rails/issues/675
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/678)
=> Foreman dependency issue (remove foreman)

CONTRIBUTING.md, README.md, docs/additional-reading/code-splitting.md, docs/additional-reading/hot-reloading-rails-development.md, docs/additional-reading/rspec-configuration.md
When making doc changes, we want the change to work on both the gitbook
and the regular github site. The issue is that non-doc files will not go
to the gitbook site, so doc references to non doc files must use the
github URL.
Links to other docs:
* When making references to doc files, use a relative URL path like:
`[Installation Overview](docs/basics/installation-overview.md)`
* When making references to source code files, use a full url path like:
`[spec/dummy/config/initializers/react_on_rails.rb](https://github.com/shakacode/react_on_rails/tree/master/spec/dummy/config/initializers/react_on_rails.rb)`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/692)
=> Doc Changes for links on gitbook

README.md, docs/additional-reading/react-router.md, docs/api/javascript-api.md, node_package/src/clientStartup.js, node_package/src/isCreateReactElementResultNonReactComponent.js, node_package/src/isRouterResult.js, node_package/src/serverRenderReactComponent.js, node_package/tests/serverRenderReactComponent.test.js, spec/dummy/Procfile, spec/dummy/app/views/pages/_header.erb, spec/dummy/app/views/pages/index.html.erb, spec/dummy/app/views/pages/rendered_html.erb, spec/dummy/client/app/components/EchoProps.jsx, spec/dummy/client/app/startup/ClientRenderedHtml.jsx, spec/dummy/client/app/startup/ServerRenderedHtml.jsx, spec/dummy/client/app/startup/clientRegistration.jsx, spec/dummy/client/app/startup/serverRegistration.jsx, spec/dummy/config/routes.rb, spec/dummy/spec/features/integration_spec.rb
This is to support React Router v4, which needs the result of calling
renderToString.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/689)
=> Added property renderedHtml to return gen func

CONTRIBUTING.md, lib/generators/react_on_rails/templates/base/base/client/package.json.tt, spec/dummy/client/package.json
hi,
I'm trying to achieve green tests on my machine.  So far I'm unsuccessful, but I've found few issues which I'd like to fix in master to help everyone else.
Thank you,
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/661)
=> Small fixes to achieve reproducible build

docs/additional-reading/heroku-deployment.md
`heroku buildpacks:add ...` will support any custom buildpacks - there's no use case for using `heroku-buildpack-multi` unless you are relying on a `.buildpacks` file to be present in the repo (which some older projects do).
In addition, https://github.com/ddollar/heroku-buildpack-multi is deprecated and is no longer being maintained. There is a maintained fork of the project at https://github.com/heroku/heroku-buildpack-multi but it isn't necessary to point people to this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/698)
=> Remove reference to heroku-buildpack-multi

CHANGELOG.md, docs/additional-reading/node-server-rendering.md, lib/generators/react_on_rails/templates/node/base/client/node/server.js
The default Node.js server file created by the generator throw errors of `undefined`. Arrow functions don't bind `this`, so it's not referencing the `handler` object as expected but the global object likely. So something like this won't work and throw an error.
```js
Handler.prototype.initialize = () => {
console.log(`Processing ${this.queue.length} pending requests`);
......
}
```
We can either use ES6 class or write something like `Handler.prototype.handle = function (connection) ...`. I'd prefer the former one.
(BTW, I'm using Node.js as backend because I'm experimenting server-side rendering with `Relay` or `Apollo` and `ExecJS` doesn't seem to support this. But with the `Node` solution, I don't like the fact that there seems to be some unnecessary communications between `Rails` and …
=> Fix incorrect "this" references of Node.js SSR

README.md, docs/basics/generator.md
Hi, the initial 8 steps for the react_on_rails installation, setup, and hello_world example, it lists localhost 3000 for the server. Foreman uses localhost 5000, and I thought it would be easier for devs that may not know this if it were included in the Readme.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/713)
=> Change local host to match foreman port 5000 on the initial setup Readme

PROJECTS.md
* Adds [CareerBuilder For Employers](https://hiring.careerbuilder.com/) to `PROJECTS.md`, as per discussion with @justin808
* React components are not in use across the entire site quite yet. For example, the homepage does not yet feature a component.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/718)
=> Add CareerBuilder For Employers Project

CHANGELOG.md, spec/dummy/app/views/pages/index.html.erb, spec/dummy/spec/features/integration_spec.rb
On running `rake`, the following spec fails:
```
1) Pages/Index All in one page Simple Component Without Redux changes name in message according to input
Failure/Error:
within(dom_selector) do
find("input").set new_text
within("h3") do
is_expected.to have_content new_text
end
end
Capybara::Ambiguous:
Ambiguous match, found 2 elements matching css "div#HelloWorld-react-component-4"
Shared Example Group: "React Component" called from ./spec/features/integration_spec.rb:47
```
The reason is a duplicate component with the id `HelloWorld-react-component-4` in `pages/index.html.erb`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/734)
=> Fix spec failing due to duplicate component

CHANGELOG.md, docs/basics/i18n.md, lib/generators/react_on_rails/templates/base/base/Procfile.dev.tt, lib/generators/react_on_rails/templates/base/base/config/initializers/react_on_rails.rb.tt, lib/react_on_rails/test_helper/ensure_assets_compiled.rb, lib/tasks/assets.rake, lib/tasks/locale.rake, spec/dummy/config/initializers/react_on_rails.rb
Solve travis CI problem in https://github.com/shakacode/react-webpack-rails-tutorial/pull/340
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/717)
=> add locale.rake

lib/generators/react_on_rails/templates/base/base/config/initializers/react_on_rails.rb.tt, lib/react_on_rails/configuration.rb, lib/react_on_rails/locales_to_js.rb, lib/react_on_rails/test_helper/ensure_assets_compiled.rb, lib/tasks/locale.rake, spec/dummy/config/initializers/react_on_rails.rb, spec/react_on_rails/configuration_spec.rb, spec/react_on_rails/locales_to_js_spec.rb
* Better error message if the value of the i18n directory is invalid.
* Added test for configuration error message.
* DRY'd up code for checking if this config value is set.
* Improved comments in sample react_on_rails.rb config file
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/748)
=> Improve i18n Integration

spec/dummy/Gemfile, spec/dummy/Gemfile.lock
The `listen` gem is needed for rails 5 apps when using the file watcher [here.](https://github.com/shakacode/react_on_rails/blob/f42e8f47af7a6b7e0f7b55d4563b236a86aba4a3/spec/dummy/config/environments/development.rb#L53)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/761)
=> Add missing listen gem

CONTRIBUTING.md, spec/dummy/client/package.json
- Explicitly lists the locations to run commands when setting up the gem for local development.
- Fixes an issue where `yarn install-react-on-rails` command used `yarn` instead of `yarn add` and failed to exectute.
Closes #736
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/737)
=> Update CONTRIBUTING.md and related files

spec/dummy/Procfile
- The `spec/dummy` `Procfile` has the hot reloading environment variable set yet loads static assets.
- Webpack assets need to be recursively removed as they have folders.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/762)
=> Fix reloading of dummy procfile assets

CHANGELOG.md, docs/additional-reading/turbolinks.md, node_package/src/clientStartup.js
This change fixes "The node you're attempting to unmount was rendered by another copy of React." error when navigating to cached page using Turbolinks.
More info can be found at https://github.com/renchap/webpacker-react/pull/14#issuecomment-282500093 and https://sevos.io/2017/02/27/turbolinks-lifecycle-explained.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/764)
=> Fix turbolinks mount event

CHANGELOG.md, Rakefile, rakelib/release.rake
Instead of gem-release's **release** command, I use **build** and **release:rubygems_push** from bundler/gem_tasks. 
Default release command of bundler consists of [the four following commands](https://github.com/bundler/bundler/blob/master/lib/bundler/gem_helper.rb#L55): 
- **build**
- **release:guard_clean**
- **release:source_control_push**
- **release:rubygem_push**
We already have implementation of "**release:guard_clean**" (checks if there is uncommitted changes) and "**release:source_control_push**" (pushes tags to vcs). I thought we have more flexibility with the current implementation, so I just replaced '**release**' command of gem-release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> Fix issue with release script

CHANGELOG.md, docs/basics/i18n.md, lib/generators/react_on_rails/templates/base/base/config/initializers/react_on_rails.rb.tt, lib/react_on_rails/configuration.rb, lib/react_on_rails/locales_to_js.rb, spec/dummy/config/initializers/react_on_rails.rb, spec/react_on_rails/configuration_spec.rb, spec/react_on_rails/locales_to_js_spec.rb
The purpose of this PR is to add option to specify directory from where to load locale files for auto generating translations.js and default.js.
I have a rather big rails app and I don't want all the locales from rails i18n load path in my translations.js, for example I don't want rails_admin or kaminari, or other rails views stuff in there.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/777)
=> i18n_yml_dir

app/helpers/react_on_rails_helper.rb, node_package/src/ReactOnRails.js, node_package/src/StoreRegistry.js, node_package/tests/ReactOnRails.test.js, node_package/tests/StoreRegistry.test.js
* Create clearHydratedStores() methods for StoreRegistry.js and ReactOnRails.js
* Add clearHydratedStores() invocation to #initialize_redux_stores helper
* Add JS tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/785)
=> Clear hydrated stores

CHANGELOG.md, app/helpers/react_on_rails_helper.rb
This bit of debugging shows the issue.
```
[1] (pry) #<#<Class:0x007f84e5bd19f8>>: 0> puts hash_or_string.to_json
"{\"comments\":[{\"id\":9,\"author\":\"xxx\",\"text\":\"xxxxxx\",\"created_at\":\"2017-01-11T08:14:10.296Z\",
[2] (pry) #<#<Class:0x007f84e5bd19f8>>: 0> puts hash_or_string
{"comments":[{"id":9,"author":"xxx","text":"xxxxxx","created_at":"2017-01-11T08:14:10.296Z",
```
We'll get the proper tests in #787.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/791)
=> Don't call to_json on string props

SUMMARY.md, docs/additional-reading/elastic-beanstalk.md
When the yarn dependency was introduced, it made asset precompilation on elastic beanstalk fail, since elastic beanstalk does not have yarn installed by default.   Added a sample .ebextensions file which installs yarn and resolves the dependency issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/790)
=> Adding Documentation About Deploying to Elastic Beanstalk with Yarn

CHANGELOG.md, app/helpers/react_on_rails_helper.rb, lib/react_on_rails/engine.rb, lib/react_on_rails/react_component/options.rb, lib/react_on_rails/version_checker.rb, node_package/src/clientStartup.js, spec/dummy/client/yarn.lock, spec/dummy/spec/helpers/react_on_rails_helper_spec.rb, spec/react_on_rails/react_component/options_spec.rb, spec/react_on_rails/version_checker_spec.rb
Because many installations did not notice issues when versions differed, we're now going to force upgrading both the gem and node package at the same time.
6.9 introduced code that would parse the props into a Hash
unnecessarily. Any customers with significant String props took a huge
performance hit from this on page rendering.
Fix is to remove the unnecessary parsing.
I believe the parsing was done so that pretty printing of the JSON could
be done. If we introduce that feature in the future, it will:
* Be configurable on whether or not to use it.
* Possibly never run in production.
See #819.
CC: @cheremukhin23 @robwise @dylangrafmyre @squadette 
Thanks @dzirtusss for finding this! AWESOME!!!
See https://github.com/shakacode/react_on_rails/commit/7ccd603683af377880d4e16f56752ac7587c38b7#d …
=> Raise if versions differ and fix performance regression for string props

CHANGELOG.md, app/helpers/react_on_rails_helper.rb, spec/dummy/spec/helpers/react_on_rails_helper_spec.rb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/823)
=> Fix to handle nil values in json_safe_and_pretty

lib/generators/react_on_rails/templates/base/base/config/webpack/paths.yml, spec/dummy/client/package.json, spec/dummy/config/webpack/paths.yml
@robwise @kaizencodes, if this passes CI, we should merge.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/834)
=> Remove unnecesary values from paths.yml

CHANGELOG.md, app/helpers/react_on_rails_helper.rb, spec/dummy/client/yarn.lock, spec/dummy/spec/features/rails_context_spec.rb, spec/dummy/spec/helpers/react_on_rails_helper_spec.rb
No more Logging in production, an issue reported in #829 
Street credit to @justin808 for tracking down the bug and @robwise for helping me write the tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/845)
=> Logging in production removed

lib/generators/react_on_rails/templates/dev_tests/spec/simplecov_helper.rb, lib/react_on_rails/git_utils.rb, lib/react_on_rails/prerender_error.rb, rakelib/release.rake, rakelib/run_rspec.rake, spec/dummy/spec/simplecov_helper.rb, spec/react_on_rails/simplecov_helper.rb
Fixing #870 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/867)
=> Update release script to update spec/dummy/package.json and fix Ruby 2.1 issues

spec/dummy/client/server-rails-hot.js
Without the change, I had the error message:
```
22:05:30 hot-assets.1 | started with pid 9115
22:05:31 hot-assets.1 | yarn run v0.24.5
22:05:31 hot-assets.1 | $ (cd client && yarn run hot-assets) 
22:05:31 hot-assets.1 | yarn run v0.24.5
22:05:31 hot-assets.1 | $ NODE_ENV=development babel-node server-rails-hot.js 
22:05:33 hot-assets.1 | Webpack HOT dev build for Rails
22:05:33 hot-assets.1 | Using a URL as contentBase is deprecated and will be removed in the next major version. Please use the proxy option instead.
22:05:33 hot-assets.1 | proxy: {
22:05:33 hot-assets.1 | 	"*": "<your current contentBase configuration>"
22:05:33 hot-assets.1 | }
22:05:33 hot-assets.1 | Using a URL as contentBase is deprecated and will be removed in the next major version. Please use the proxy option …
```
=> Remove contentBase deprecation warning message

CHANGELOG.md, README.md, lib/generators/react_on_rails/templates/base/base/client/app/bundles/HelloWorld/components/HelloWorld.jsx, lib/generators/react_on_rails/templates/redux/base/client/app/bundles/HelloWorld/startup/HelloWorldApp.jsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/886)
=> Update railsContext documentation and fix generator

CHANGELOG.md, lib/generators/react_on_rails/templates/base/base/client/package.json.tt, spec/react_on_rails/support/shared_examples/base_generator_examples.rb
**WORK DONE**
1. The package.json file created by the generator now creates minified javascript production builds by default. This was done by adding the -p flag to webpack on the build:production script.
2. A test was added to verify that the build:production script includes the -p flag.
**NOTES**
1. I deleted the previous PR and created a new one because I squashed and rebased to keep the project history clean.
2. Sorry for the delay, it took me a while to wrap my head around the development setup and the codebase.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/895)
=> Generated client/package.json creates production builds using webpack by default

CHANGELOG.md, lib/react_on_rails/git_utils.rb, spec/react_on_rails/git_utils_spec.rb
- Fix for GitUtils.uncommitted_changes? throwing an error when called in
an environment that does not have git installed
- Add tests for GitUtils.uncommitted_changes? scenariors
- Fixes #888
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/889)
=> Update #uncommitted_changes? to handle missing Git

CHANGELOG.md, Gemfile, lib/react_on_rails/utils.rb, lib/react_on_rails/version.rb, lib/react_on_rails/version_checker.rb, package.json, spec/dummy/Gemfile, spec/dummy/Gemfile.lock, spec/dummy/client/package.json, spec/dummy/client/yarn.lock
Uses new helper pack_path to get the path of the server bundle without
worrying about any CDN set in the asset_host.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/901)
=> Update WebpackerLite 2.1 fixes server rendering

lib/generators/react_on_rails/base_generator.rb, spec/react_on_rails/generators/install_generator_spec.rb
The name of the pack tag in the generated webpack config is webpack_bundle, not main.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/911)
=> Fixed typo in install generator message

CHANGELOG.md, lib/generators/react_on_rails/base_generator.rb, spec/react_on_rails/generators/install_generator_spec.rb, spec/react_on_rails/support/shared_examples/base_generator_examples.rb
keep blank line at top in case existing .gitignore does not end in a
newline
If file ended with the `coverage` line below and no newline at the end, this got generated:
```
#lib genrerated from simplecov
coverage# React on Rails
npm-debug.log*
node_modules
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/916)
=> Handle case of existing gitignore no newline end

CONTRIBUTING.md
$ yarn add phatomjs
says
warning phantomjs@2.1.7: Package renamed to phantomjs-prebuilt. Please update 'phantomjs' package references to 'phantomjs-prebuilt'
So do like it says.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/930)
=> Use 'phantomjs-prebuilt'

lib/generators/react_on_rails/dev_tests_generator.rb
The usage was removed in the following commit:
https://github.com/shakacode/react_on_rails/commit/fcd6e28c2921a51c0b110cf3f773c42e93c7b95e
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/936)
=> Removes unused constant

CHANGELOG.md, lib/generators/react_on_rails/templates/base/base/Procfile.dev-server
Otherwise, the default generator doesn't work with the
webpack-dev-server.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/940)
=> Add information on the --inline option

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/944)
=> Fix typo in React Rails 9.x upgrade instructions

CHANGELOG.md, spec/react_on_rails/generators/generator_messages_spec.rb
Without this `require` statement, the following error has thrown:
$ bundle exec rspec spec/react_on_rails/generators/generator_messages_spec.rb
An error occurred while loading ./spec/react_on_rails/generators/generator_messages_spec.rb.
Failure/Error:
describe GeneratorMessages do
it "has an empty messages array" do
expect(GeneratorMessages.messages).to be_empty
end
it "has a method that can add errors" do
GeneratorMessages.add_error "Test error"
expect(GeneratorMessages.messages)
.to match_array([GeneratorMessages.format_error("Test error")])
end
NameError:
uninitialized constant GeneratorMessages
No examples found.
Finished in 0.00026 seconds (files took 0.12917 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples
---
This change is [<img …
=> Fix to add missing dependency to run generator spec individually

CHANGELOG.md, lib/react_on_rails/configuration.rb, lib/react_on_rails/locales_to_js.rb, spec/react_on_rails/configuration_spec.rb, spec/react_on_rails/locales_to_js_spec.rb
fixed and improved configuration checks broken by #899
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/967)
=> Improved configuration checks

CHANGELOG.md, lib/react_on_rails/server_rendering_pool/exec.rb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/963)
=> Typo in rescue for server rendering

.eslintrc, CHANGELOG.md, package.json, spec/react_on_rails/generators/install_generator_spec.rb, spec/react_on_rails/support/generator_spec_helper.rb, yarn.lock
These dependencies are injected by generator spec.
However they are unnecessary for released react-on-rails package.
Even if the `dependencies` section is removed, it will back after `$ rspec spec/react_on_rails/generators/install_generator_spec.rb` is run.
I think it is unexpected behavior.
So I removed these dependencies and fix specs.
@Judahmeek @justin808
Can you review this PR? It this a correct way?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/968)
=> Remove unnecessary dependencies from released NPM package

node_package/src/ReactOnRails.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/987)
=> Comment typo fix "...in tha..." -> "..in that..."

CHANGELOG.md
Docs link provided in relative form, per instructions in `CONTRIBUTING.md`. Let me know if I overlooked anything!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1003)
=> Fix broken link to 8.x -> 9.x upgrade instructions

CHANGELOG.md, lib/react_on_rails/utils.rb, spec/react_on_rails/utils_spec.rb
Utils.bundle_js_file_path was incorrectly returning
`'manifest.json'`
instead of, say,
`'/path/to/rails/public/packs/manifest.json'`
Fixes #1011
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1012)
=> Fix Utils.bundle_js_file_path for manifest.json in webpacker projects

lib/generators/react_on_rails/templates/base/base/app/javascript/bundles/HelloWorld/components/HelloWorld.jsx
After the new facebook docs update the link to set initial state in ES6 Class has changed to https://reactjs.org/docs/state-and-lifecycle.html#adding-local-state-to-a-class
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1017)
=> Updated HelloWorld.jsx

CHANGELOG.md, README.md, docs/additional-reading/caching-and-performance.md, docs/api/ruby-api.md, lib/react_on_rails/utils.rb, spec/react_on_rails/utils_spec.rb
Added 2 cache helpers:
ReactOnRails::Utils.bundle_file_name(bundle_name)
ReactOnRails::Utils.server_bundle_file_name
for easy access to the hashed filenames for use in cache keys
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1018)
=> Added 2 helpers to get hashed file names

CHANGELOG.md, lib/react_on_rails/server_rendering_pool/exec.rb
Latest release does not display the actual error when server-rendering fails.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1020)
=> Fix server rendering rescue

.travis.yml
This change adds Ruby 2.5.0 to Travis configuration.  Last time I worked on react_on_rails a year ago I had some issues with 2.5.0 in CI, I'm glad to see that it works nowadays.
I did not test with 2.5.0 in production, but adding to CI would be a good first step.
Please consider applying.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1026)
=> Test in Ruby 2.5.0

CHANGELOG.md, node_package/src/clientStartup.js, node_package/src/createReactElement.js
Looks like this was originally addressed in #1013, but was closed by accident and never reopened. My project is using React 16 and I can confirm that this patch prevents the deprecation warning.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1028)
=> Use ReactDOM.hydrate() for hydrating a SSR component if available

CHANGELOG.md, lib/react_on_rails/version_checker.rb
If you accidentally put "react-on-rails": "9.0.x" in your `package.json`, you will get a stack trace.
This commit helps you during upgrade and reports error in a readable way.
Closes #489.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1025)
=> Report error in parsing version number

app/helpers/react_on_rails_helper.rb
Many folks using the SSR features of react-on-rails are doing so in order to improve SEO while simultaneously improving user experience.
It is commonly recommended to have key content rendered into the HTML at the earliest possible point. From what I understand, there is no need for the specification tag/script to come before the rendered content and simply swapping the order can have a significant impact on the content that fits within the 100kb "SEO optimized" page size.
e.g. if I have 50kb of state data followed by 100kb of the actual rendered HTML, the bottom half of the page may not get indexed by e.g. Google.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1 …
=> Place the rendered output before the spec tag

CHANGELOG.md, lib/react_on_rails/locales_to_js.rb, spec/react_on_rails/fixtures/i18n/locales/en.yml, spec/react_on_rails/locales_to_js_spec.rb, spec/spec/examples.txt
Changed i18n parsing to convert ruby i18n argument syntax into FormatJS argument syntax to fix #1021
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1046)
=> FormatJS i18n argument parsing

CHANGELOG.md, lib/react_on_rails/utils.rb, spec/react_on_rails/test_helper/webpack_assets_compiler_spec.rb
Closes #1044. This fixes an issue where the test runner fails if you have spaces in your path. 
This PR uses Regexp to escape the path before the command is run.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1045)
=> Make sure the path is correctly escaped in case it contains spaces.

CHANGELOG.md, lib/generators/react_on_rails/templates/base/base/config/initializers/react_on_rails.rb
Hi,
Recently webpacker gem has been updated in a way to make `NODE_ENV` not fallback to `RAILS_ENV`(https://github.com/rails/webpacker/commit/e61618465f872694775d1a39c10cf55d9df939ea).
By default react_on_rails generates this config:
```ruby
config.build_production_command = 'RAILS_ENV=production bin/webpack'
```
Before the change in webpacker, this was effectively setting both `RAILS_ENV` and `NODE_ENV` to "production", but not anymore. Now `NODE_ENV` defaults to "development". So if you don't specify it, your production assets will be compiled using dev settings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1053)
=> Specify NODE_ENV in the production build command

README.md
Fix a link in `README.md` so that it points to `https://github.com/reactjs/react-router`.
This is a very minor issue. I ran into it when I clicked on the link in the readme and ended up on the wrong page.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1056)
=> Fix React Router link

CHANGELOG.md, README.md, lib/generators/react_on_rails/base_generator.rb, lib/react_on_rails/version_checker.rb, rakelib/release.rake, spec/dummy/Gemfile.lock, spec/react_on_rails/fixtures/semver_caret_package.json, spec/react_on_rails/fixtures/semver_tilde_package.json, spec/react_on_rails/version_checker_spec.rb
We keep the react_on_rails gem and the react-on-rails node package at
the same exact versions so that we can be sure that the interaction
between them is precise.
This is so that if a bug is detected after some update, it's critical that
both the gem and the node package get the updates.
This change ensures that the package.json specification does not use a
~ or ^ as reported in https://github.com/shakacode/react_on_rails/issues/1062
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1063)
=> More exact version checking

CHANGELOG.md, lib/react_on_rails/assets_precompile.rb, spec/react_on_rails/assets_precompile_spec.rb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1064)
=> Use most recent sprockets manifest

CHANGELOG.md, README.md, lib/react_on_rails/react_on_rails_helper.rb, lib/react_on_rails/utils.rb, spec/dummy/app/views/pages/broken_app.html.erb, spec/dummy/app/views/pages/react_helmet.erb
* Makes no sense to have react_component_hash not use prerrender.
* Fixed issue where checking gem existence.
* Added docs for react_component_hash
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1077)
=> react_component_hash always has pre-render true

spec/dummy/Gemfile.lock
When running `bin/setup` as suggested in the [contributing guide](https://github.com/shakacode/react_on_rails/blob/fa52ac65d0248e002dd7fb4b22e1fec7a84aebd4/CONTRIBUTING.md#prereqs), the Gemfile.lock gets automatically updated to the newest react_on_rails version. This should point to the newest version already.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1085)
=> Update react_on_rails gem version

.travis.yml, lib/react_on_rails/react_on_rails_helper.rb, spec/dummy/Gemfile.lock, spec/dummy/spec/helpers/react_on_rails_helper_spec.rb, spec/dummy/yarn.lock
Now, conversion of props works for HashWithIndifferentAccess. Previously
crashed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1100)
=> HashWithIndifferent access for props threw

lib/react_on_rails/test_helper/webpack_assets_status_checker.rb, lib/react_on_rails/utils.rb, lib/react_on_rails/webpacker_utils.rb, spec/dummy/spec/rails_helper.rb, spec/react_on_rails/configuration_spec.rb, spec/react_on_rails/fixtures/webpack_assets/assets_with_manifest_exist_server_bundle_separate/compiled_js/manifest.json, spec/react_on_rails/spec_helper.rb, spec/react_on_rails/test_helper/webpack_assets_status_checker_spec.rb, spec/react_on_rails/utils_spec.rb
Review in #1093. 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1102)
=> fix test helper

CHANGELOG.md, node_package/src/clientStartup.js, spec/dummy/app/views/layouts/application.html.erb
Fixes #290, transparently handling <script async> tag. If the document was already loaded,
the DOMContentLoaded event handler no longer fires, so we just execute it directly, the
same way as jQuery does in $.ready().
Co-authored-by: Alexey Makhotkin
Discussion in #1099.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1107)
=> Handle <script async> transparently #1099

lib/react_on_rails/prerender_error.rb
Long props result in very long error messages. This change truncates
the props and code to 1,000 chars
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1117)
=> Don't log full props or JS code

lib/react_on_rails/prerender_error.rb, lib/react_on_rails/utils.rb, spec/react_on_rails/utils_spec.rb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1118)
=> Added smart_trim method for better logging

lib/react_on_rails/helper.rb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1120)
=> Always clear hydrated stores inside the server-side rendering worker

lib/react_on_rails/configuration.rb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1128)
=> #1127 `TRUE` was deprecated in ruby 2.4, using `true` instead.

docs/basics/configuration.md, lib/react_on_rails/configuration.rb, lib/react_on_rails/test_helper.rb, lib/react_on_rails/utils.rb, lib/react_on_rails/webpacker_utils.rb, spec/react_on_rails/test_helper/webpack_assets_compiler_spec.rb, spec/react_on_rails/utils_spec.rb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1133)
=> Test improvements

lib/react_on_rails/utils.rb
For some reason, Gem::Specification.find_by_name("webpacker") doesn't identify Webpacker 4 prereleases like webpacker 4.0.0.pre.pre.2 while Gem::Specification.find_all_by_name("webpacker") does. I've tested Gem::Specification.find_all_by_name for possible undesired side-effects, like returning multiple results for Gem::Specification.find_all_by_name("react"), and it has worked as desired in all cases that I've tested it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1134)
=> Add support for webpacker 4 prereleases

CHANGELOG.md, node_package/.babelrc, package.json, yarn.lock
Don't apply babel-plugin-transform-runtime inside react-on-rails to work with babel@7
It should be applied by user land.
Why?
The generated code depends on built babel's version.
It means that user couldn' build their code with babel@7 that depends on react-on-rails built by babel@6.
For example, babel-plugin-transform-runtime (babel 6) generates the 
following code.
``` js
var _assign = require('babel-runtime/core-js/object/assign');
```
However @babel/plugin-transform-runtime (babel 7) expects the 
path that beginning of `@babel/runtime/`.
The change allows to use react-on-rails on babel@7.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1136)
=> Don't apply babel-plugin-transform-runtime inside react-on-rails to work with babel 7

CHANGELOG.md, lib/react_on_rails/locales_to_js.rb, spec/react_on_rails/fixtures/i18n/locales/en.yml, spec/react_on_rails/locales_to_js_spec.rb
Fixes #1126
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1129)
=> Ignore Arrays in Rails i18n yml files

CHANGELOG.md, node_package/src/clientStartup.js
This fixes a regression introduced by [PR 1099](https://github.com/shakacode/react_on_rails/pull/1099), explained in [issue 1150](https://github.com/shakacode/react_on_rails/issues/1150).  The potential for this issue [was raised](https://github.com/shakacode/react_on_rails/pull/1099#issuecomment-397938518) during review of PR 1099 but not reproduced at that time, and is currently only reproducible for us in Chrome when utilizing `defer`ed scripts which are preloaded.
The code was cloned from jQuery `$.ready()`, with the offending part of the condition existing to support IE versions < 9.  This PR introduces a backwards-compatibility-break for those versions of IE, but should have no impact on any non-EOL browsers other than resolving this bug.
---
This change is [<img …
=> Fix render during interactive readyState

CHANGELOG.md, node_package/src/clientStartup.js
This is a follow-up to [PR 1151](https://github.com/shakacode/react_on_rails/pull/1151).  I apologize for doubling up on this, but the last change was insufficient and we've found additional edge cases of undesired behavior with aggressive preloading of deferred scripts.
In addition to solving behavior for non-turbolinks users, this change also restores the original intent of `clientStartup()`, which explicitly calls out the turbolink check as needing to be done AFTER page load.  Since [PR 1099](https://github.com/shakacode/react_on_rails/pull/1099) this check has potentially been done prior to load.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1152)
=> Fix failure to render during interactive readyState

CHANGELOG.md, lib/react_on_rails/locales_to_js.rb, spec/react_on_rails/fixtures/i18n/locales/en.yml, spec/react_on_rails/locales_to_js_spec.rb
Fixed intl parsing bug when trying to parse non-string entries.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1153)
=> Fixed intl parsing bug when trying to parse non-string entries

CHANGELOG.md, docs/basics/configuration.md, lib/react_on_rails/helper.rb, lib/react_on_rails/server_rendering_pool/ruby_embedded_java_script.rb, lib/react_on_rails/utils.rb, lib/react_on_rails/webpacker_utils.rb, spec/dummy/Procfile.static, spec/dummy/client/yarn.lock, yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1173)
=> Enable webpack-dev-server with SSR

CHANGELOG.md, docs/api/view-helpers-api.md, docs/basics/configuration.md, lib/react_on_rails/configuration.rb
Default for prerender_error to show errors during development.
config.raise_on_prerender_error = Rails.env.development?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1145)
=> Update configuration.md and default config.raise_on_prerender_error = Rails.env.development?

CONTRIBUTING.md, README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1181)
=> Fix several typos in README file

CHANGELOG.md, lib/react_on_rails/react_component/render_options.rb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1213)
=> Add method for retrieving any option from render_options or nil instead

rakelib/example_type.rb, rakelib/examples.rake
Since Rails 5.1+ you can find the option the new projects `rails new foo --webpack`. 
After the Rails 6.0 webpack should be installed by default.
Environment:
Ruby 2.6.1p33 (2019-01-30 revision 66950) [x86_64-darwin18]
Rails 5.2.3
Steps to reproduce:
`$ rake`
error message
```
(...cut)
cd /Users/mike/proj/react_on_rails/gen-examples/examples/basic && touch .gitignore
cd /Users/mike/proj/react_on_rails/gen-examples/examples/basic && rake webpacker:install
rake aborted!
Don't know how to build task 'webpacker:install' (See the list of available tasks with `rake --tasks`)
(See full trace by running task with --trace)
rake aborted!
Command failed with status (1): [cd /Users/mike/proj/react_on_rails/gen-exa...]
/Users/mike/proj/react_on_rails/rakelib/task_helpers.rb:22:in `block in sh_in_dir' …
```
=> Add webpacker for Rails 5.1+ in tests

.prettierrc, README.md, docs/basics/render-functions-and-railscontext.md, lib/react_on_rails/utils.rb, lib/react_on_rails/webpacker_utils.rb, node_package/src/createReactOutput.ts, package-scripts.yml, package.json, spec/dummy/app/views/pages/context_function_return_jsx.html.erb, spec/dummy/app/views/shared/_header.erb, spec/dummy/client/app/components/ContextFunctionReturnInvalidJSX.jsx, spec/dummy/client/app/packs/clientRegistration.jsx, yarn.lock
to return JSX and detcting that
If you were a user of React on Rails, would you mind the small required changes to ensure correct functionality? In other words, we will always call React.createElement in the library, rather than just taking JSX from some function that took props and was invoked by React on Rails.
See the discussion here: 
https://github.com/shakacode/react_on_rails/issues/1198#issuecomment-623967098
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1280)
=> Allowing a render function to return JSX and console.error a message.

CHANGELOG.md, docs/basics/configuration.md, docs/basics/hmr-and-hot-reloading-with-the-webpack-dev-server.md, docs/basics/rspec-configuration.md, docs/basics/upgrading-react-on-rails.md, docs/tutorial.md, lib/generators/react_on_rails/templates/base/base/Procfile.dev-hmr, lib/generators/react_on_rails/templates/base/base/config/initializers/react_on_rails.rb, lib/tasks/assets.rake, spec/dummy/Procfile.spec, spec/dummy/bin/webpack-dev-server, spec/dummy/config/initializers/react_on_rails.rb
If the webpacker webpack config files exist, then React on Rails
will not override the default assets:precompile setup by rails/webpacker
The fix is to remove the JS files inside of config/webpack,
like config/webpack/production.js.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1298)
=> Default to rails/webpacker precompile

.github/workflows/main.yml, lib/generators/react_on_rails/templates/dev_tests/spec/rails_helper.rb
```
run_rspec:all_but_examples
run_rspec:examples
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1326)
=> Improve Github actions

CHANGELOG.md, CONTRIBUTING.md, node_package/src/clientStartup.ts
Async script loading optimizes page load speed. With this fix, a bundle
can be loaded "async" and a handler function can determine when to hydrate.
See https://github.com/shakacode/react_on_rails/blob/master/docs/api/view-helpers-api.md#renderer-functions-function-that-will-call-reactdomrender-or-reactdomhydrate
For an example of this, see the docs for loadable-components SSR
https://loadable-components.com/docs/server-side-rendering/#4-add-loadableready-client-side
Loadable-Components is supported by React on Rails Pro:
https://www.shakacode.com/react-on-rails-pro
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1327)
=> Proper loading of asynch script setup

lib/tasks/assets.rake
Setting NODE_ENV here interferes with Rails'/webpacker's control of this
variable, particularly in production. In particular, this means that
compiling assets in production using
`bundle exec rails assets:precompile` uses the development webpacker
configuration rather than the production one.
1. NODE_ENV is not set when running precompile
2. React on Rails sees it's empty and sets to development
3. rails/webpacker does not apply default of production
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1356)
=> Don't set NODE_ENV in assets.rake

CHANGELOG.md, docs/basics/configuration.md, lib/tasks/assets.rake, spec/dummy/spec/rake/assets_rake_spec.rb
Added the ability to assign a module with a `call` method to `config.build_production_command`.
See the configuration docs ./docs/basics/configuration.md.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1363)
=> Ability to use a module for `config.build_production_command`

CHANGELOG.md
The URL for described changes in 12.0.2 release was pointing to the wrong PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1373)
=> Update changelog reference for 12.0.2

CHANGELOG.md, node_package/src/ReactOnRails.ts, node_package/src/clientStartup.ts, spec/react_on_rails/react_component/render_options_spec.rb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1374)
=> Added support for @hotwired/turbo.

node_package/src/ReactOnRails.ts
It fixes the following Typescript error:
```
error TS2345: Argument of type '{ traceTurbolinks: true; turbo: boolean; }' is not assignable to parameter of type '{ traceTurbolinks: boolean; }'.
Object literal may only specify known properties, and ''turbo'' does not exist in type '{ traceTurbolinks: boolean; }'.
```
That happens on this code:
```ts
ReactOnRails.setOptions({
'traceTurbolinks': true,
'turbo': true
})
```
Due to the fact that the `options` type is inferred by `DEFAULT_OPTIONS`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1377)
=> Fix TypeScript error

lib/react_on_rails/helper.rb, lib/react_on_rails/server_rendering_pool/ruby_embedded_java_script.rb
Per https://github.com/scoutapp/scout_apm_ruby/blob/master/lib/scout_apm/tracer.rb
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1379)
=> Scout APM Instrument React SSR methods

.circleci/config.yml, CHANGELOG.md, docs/guides/how-react-on-rails-works.md, docs/rails/rails-engine-integration.md, lib/tasks/assets.rake
Fixes #1368.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1371)
=> Allow setting REACT_ON_RAILS_PRECOMPILE to false to skip building

CHANGELOG.md, lib/react_on_rails/helper.rb, lib/react_on_rails/server_rendering_pool/ruby_embedded_java_script.rb, node_package/babel.config.js, node_package/src/ReactOnRails.ts, node_package/src/clientStartup.ts, node_package/src/createReactOutput.ts, node_package/src/isServerRenderResult.ts, node_package/src/serverRenderReactComponent.ts, node_package/src/types/index.ts, node_package/tests/serverRenderReactComponent.test.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1380)
=> WIP: Enable registered components to return promises for server rendering by React on Rails Pro Node Renderer

node_package/src/ReactOnRails.ts, node_package/src/clientStartup.ts, node_package/src/reactHydrate.ts, node_package/src/reactRender.ts, node_package/src/supportsReactCreateRoot.js
With React 18, the client-side rendering process has been updated.  To prepare the way for supporting React 18's features, the new way of rendering needs to be adopted.
This change creates some helpers that support both methods of rendering and hydrating on the client to start the path forward to supporting React 18.
NOTE: Because there is no current support for testing against React versions, I am forgoing adding extra tests for this.  If there is an approach to doing this, we can add that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1409)
=> Add support for React 18 server rendering

CHANGELOG.md, docs/deployment/heroku-deployment.md, docs/guides/configuration.md, docs/guides/how-react-on-rails-works.md, lib/tasks/assets.rake
Update logic on what build command to use in assets:precompile to be based on whether or not
config.build_production_command is defined.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1402)
=> Change custom precompile to check ReactOnRails.configuration.build_production_command present?

lib/react_on_rails/configuration.rb, lib/tasks/assets.rake, lib/tasks/locale.rake, spec/dummy/config/initializers/react_on_rails.rb, spec/dummy/spec/initialized_configuration_spec.rb, spec/react_on_rails/configuration_spec.rb
The only way I found to actually test the logic of `assets.rake` with an un-initialized Rails application was by using `bundle exec irb`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1415)
=> Move webpacker task adjustment logic to Configuration class method

lib/react_on_rails/helper.rb
Comparing the names is much less efficient than comparing the instance directly.
It may also change in the future: https://bugs.ruby-lang.org/issues/18576
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1433)
=> Stop checking encoding names

CHANGELOG.md, Gemfile.development_dependencies, docs/guides/client-vs-server-rendering.md, docs/guides/configuration.md, docs/guides/tutorial.md, docs/javascript/server-rendering-tips.md, lib/generators/react_on_rails/base_generator.rb, spec/dummy/Gemfile.lock
Closes #1438 
Supersedes and closes #1437 
Removes `mini_racer` addition as `Node.js` runtime will be picked up automatically and used if present (and it needs to be for NPM dependencies installs)
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1453)
=> Remove mini_racer as the default ExecJS runtime

node_package/src/buildConsoleReplay.ts, node_package/src/clientStartup.ts, node_package/src/serverRenderReactComponent.ts
Due to https://devblogs.microsoft.com/typescript/announcing-typescript-4-4/#use-unknown-catch-variables,
some TypeScript files failed to compile under TS 4.4 or later.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1444)
=> Update catch types to be any for TypeScript 4.4

lib/generators/react_on_rails/templates/base/base/app/views/layouts/hello_world.html.erb
The page title appears as `ReactOnRailsWithWebpacker` which can be changed to `ReactOnRailsWithShakapacker`.
Refer this image:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1467)
=> Replaced page title Webpacker text with Shakapacker

spec/react_on_rails/react_component/render_options_spec.rb
With the Ruby 2.7 version we are facing the below warning:
When using Ruby 3.1.2 the test will break with the below error:
Raised this PR to fix the warning in the `render_options_spec` file. We won't face any issues in Ruby 3+ versions.
Reference article: https://blog.saeloun.com/2019/10/07/ruby-2-7-keyword-arguments-redesign.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1479)
=> Removed keyword parameters warning. This will raise error in Ruby 3+ version.

CHANGELOG.md, docs/api/javascript-api.md, node_package/src/ReactOnRails.ts, node_package/src/types/index.ts
`reactHydrateOrRender` is a useful utility for projects with SSR. Also, it takes care of using the correct version of react API. Which is important for projects migrating to react 18.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1481)
=> exposing reactHydrateOrRender api

node_package/src/types/index.ts
The `throwIfMissing` param of `getStore` should be optional as it defaults to `true` https://github.com/shakacode/react_on_rails/blob/35d9d6943f4b52b652c6142a8aa5ef0f8ca36f70/node_package/src/ReactOnRails.ts#L73
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1480)
=> Fixing wrong type

docs/guides/tutorial.md
The current command creates a project with the name of `--skip-turbolinks` rather taking it as an option.
As per rails documentation, options comes at the end, after the APP_PATH:
`rails new APP_PATH [options]`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1490)
=> Update order of args in rails new command

.github/workflows/main.yml
In this PR I have resolved two issues:
- We have indirect dependency to `psych`. In their recent major release (5.0.0), `libyaml` is not bundled with the gem so it relies on this library to be installed on the system.
- We have dependency to `ffi` which requires `libffi` version 7 to be available on the system. Since Ubuntu 20.10, we have version 8 of this library. So I used `ubuntu-20.04` instead of `ubuntu-latest` to ensure we have this library on the host machine.
This should resolve CI issues on #1491 and #1495.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1497)
=> Fix broken CI

CHANGELOG.md, node_package/src/clientStartup.ts
In `reactOnRailsPageLoaded`, if we finds no react component, the function [return ](https://github.com/NhanHo/react_on_rails/blob/f121906bf94a7f84ad4dde20c1cd7e93fa75f550/node_package/src/clientStartup.ts#L209) and `context.roots` is not initialized. This cause `findContext().roots` in `reactOnRailsPageUnloaded` to be undefined, and `for .. of` throws an exception.
This should mostly affect app using both hotwire and react_on_rails, as the recommended way to load js is to do the same file everywhere, otherwise the issue can be avoided by just not loading react_on_rails
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1498)
=> Fix reactOnRailsPageUnloaded when there is no component on the page

spec/dummy/README.md
There is no `yarn rescript:build` command. This line is replaced with the correct one:
`yarn build:rescript`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1501)
=> Fix rescript build command

docs/guides/configuration.md, lib/react_on_rails/configuration.rb, spec/react_on_rails/configuration_spec.rb
Since `shakapacker` configuration might eventually run prior to the `react_on_rails` configuration, settings `ENV["WEBPACKER_PRECOMPILE"] = "false"` might not give the expected result. In order to make this behaviour consistent, we wan't gem users to specify `webpacker_precompile: false` in the `config/webpacker.yml` file.
New error message:
```
RAILS_ENV=production NODE_ENV=production rake assets:precompile 1 ↵ ✹ ✭
rake aborted!
React on Rails and Shakapacker error in configuration!
In order to use config/react_on_rails.rb config.build_production_command,
you must edit config/webpacker.yml to include this value in the default configuration:
'webpacker_precompile: false'
Alternatively, remove the config/react_on_rails.rb config.build_production_command and the
default bin/webpacker script …
```
=> Provide error message when setup conflicts with Shakapacker

lib/generators/react_on_rails/templates/base/base/config/initializers/react_on_rails.rb
I noticed `configuration.md` link in initializer template file is old. So I changed it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1512)
=> change config link from `basics` to `guides`

CHANGELOG.md, lib/react_on_rails/helper.rb, lib/react_on_rails/packs_generator.rb, spec/dummy/spec/packs_generator_spec.rb
This PR fixes the bug as described in the Issue: https://github.com/shakacode/react_on_rails/issues/1510
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1511)
=> Update Helper to Check for Bundle with correct Extension

CHANGELOG.md, lib/react_on_rails/helper.rb, lib/react_on_rails/packs_generator.rb, lib/react_on_rails/test_helper/webpack_assets_status_checker.rb, lib/react_on_rails/utils.rb, lib/react_on_rails/version.rb, package.json, spec/dummy/Gemfile.lock, spec/dummy/spec/packs_generator_spec.rb
Currently, The Generate Pack Script handles the on-demand generation of packs only for existing components by checking m_time to verify if the generated packs are stale. If a user creates a new Component under `components_subdirectory,` It's not tracked by `stale_generated_component_packs`; 
This PR updates the FS-based Pack generation feature by adding a check for missing_packs. The system will generate a new pack when either the components are stale, or a new component is created.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1506)
=> Generate Pack if Missing Generated Pack for Registered Component

docs/guides/installation-into-an-existing-rails-app.md
Updated the instruction to refer to `shakapacker` rather `webpacker`.
I recommend merging #1491 before this instruction and updating this guide based on those changes otherwise, we need to make a new PR.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1495)
=> Update instruction on an existing Rails app

lib/react_on_rails/utils.rb, lib/react_on_rails/webpacker_utils.rb, spec/react_on_rails/webpacker_utils_spec.rb
Refactoring in [PR1509](https://github.com/shakacode/react_on_rails/pull/1509/files#diff-76ac9622c1c83bf5694255c2474bfb0b9a68954e8598e475fc123ed7910874fb) introduced follwing bugs: 
- The refactor created `semver_to_string` method in `ReactOnRails::Utils` but they were referenced using `ReactOnRails::WebpackerUtils`
- `shackapacker_version_requirement_met?` is checking minimum version >= installed version whereas we want to check installed_version > minimum_version. Further, the logic will fail when a required version is 6.5.3 and the installed is 6.6.1.
This PR addresses these critical bugs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1515)
=> Fix Misc Bugs Introduced in Pack Generator Refactoring

lib/react_on_rails/helper.rb
- Having `ApplicationController.helpers.append_(stylsheet/javascript)_pack_tags` breaks Components registration for Application using `content_for` for rendering partials containing react copmonents in views.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1516)
=> Remove `ApplicationController.helpers` for append_tags

CHANGELOG.md, docs/guides/rails-webpacker-react-integration-options.md
- Add documentation for suppressing warning messages related to `Module not found: Error: Can't resolve 'react-dom/client'`
- Improve clarity of old entries in changelog
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1528)
=> Add docs for ignoring warning related to react dom client not found

spec/dummy/spec/packs_generator_spec.rb
While running `react_on_rails:generate_packs` I saw an error that pointed me at a documentation page that was no longer available. This PR updates all of these outdated links in the file. where this error was raised.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1534)
=> Update documentation links

README.md
Fixes the link to https://www.shakacode.com/react-on-rails/docs/guides/file-system-based-automated-bundle-generation/ in the readme.
_Add the CHANGELOG entry at the top of the file._
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1535)
=> Fix link to automated bundling in readme

CHANGELOG.md, node_package/src/clientStartup.ts, spec/dummy/app/views/layouts/application.html.erb, spec/dummy/config/initializers/react_on_rails.rb, spec/dummy/spec/helpers/react_on_rails_helper_spec.rb
Fixed the race condition revealed by https://github.com/shakacode/react_on_rails/pull/1539
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1540)
=> Make sure renderInit only runs after DOMContentLoaded

docs/guides/file-system-based-automated-bundle-generation.md
I want to make sure that any issues, such as this potential yak shave, are as visible as possible.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1542)
=> Raise visibility of CI integration section for generated packs

CHANGELOG.md, docs/guides/file-system-based-automated-bundle-generation.md, lib/react_on_rails/helper.rb, spec/dummy/spec/helpers/react_on_rails_helper_spec.rb
Instead of creating an `append_X_pack` call  conditional on the existence of the generated pack entrypoint, the new logic will always create the `append_X_pack` call for the component as long as the component's render option's `auto_load_bundle` is `true` in `test` or `production` environments.
In the development environment, however, a missing generated pack entrypoint will result in a raised error message.
_Remove this paragraph and mention any other important and relevant information such as benchmarks._
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1545)
=> Always generate append_X_pack calls if not in development

.github/workflows/main.yml
Similar to Shakapacker and ReactRails, we need to include `pull_request` as a CI trigger for GitHub actions so that the `main` workflow gets run if other contributors than the officials open a new PR.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1553)
=> Include PR as a trigger for CI for main workflow

CHANGELOG.md, lib/react_on_rails/server_rendering_js_code.rb, lib/react_on_rails/server_rendering_pool/ruby_embedded_java_script.rb, node_package/src/serverRenderReactComponent.ts
The current implementation calls `ExecJS::Runtime#eval` twice during every react server-side render, but we can refactor it to only call `eval` once.
This causes a 2x speedup (e.g. 800ms -> 400ms) with the Node.js runtime, and other runtimes with slow IO.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1544)
=> remove extra js eval call

Gemfile.development_dependencies, spec/dummy/Gemfile.lock, spec/dummy/spec/support/selenium_logger.rb
This PR removes the `webdrivers` gem as suggested by the `webdrivers`' maintainer in [this comment](https://github.com/titusfortner/webdrivers/issues/247#issuecomment-1641139415).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1560)
=> Remove webdrivers

CHANGELOG.md, lib/react_on_rails/packs_generator.rb, spec/dummy/spec/packs_generator_spec.rb, spec/dummy/spec/system/integration_spec.rb
Verifies that the `component_subdirectory` is set before generating packs. This is especially important when running the `assets:precompile` task.
Fixes #1566 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1567)
=> Packs generator subdirectory check

.github/workflows/package-js-tests.yml, package.json, yarn.lock
As an end user of react_on_rails we ran some checks on external dependencies and noticed the outdated `concurrently` dependency. After investigating I noticed the `concurrently` dependency is only used for linting/formatting tasks in package-scripts.yml. Moving it to devDependencies removes an unnecessary dependency for end users.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1571)
=> Upgrade concurrently package and move to devDependencies

docs/additional-details/generator-details.md
I just noticed this part in the docs, which seems to be removed a long time ago.
I think we must have relevant entries in Changelog. Since it is an old change, it might not be critical to do so.
Any thought?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1575)
=> Remove Bootstrap option from generator docs

.github/workflows/lint-js-and-ruby.yml, .github/workflows/main.yml, .github/workflows/package-js-tests.yml, .github/workflows/rspec-package-specs.yml
Disabling persisted credentials is a nice-to-have security improvement - it's very unlikely to ever actually be exploitable for this codebase, but might as well disable it nonetheless; see https://github.com/actions/checkout/issues/485 for more.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1578)
=> ci: update actions and disable persisted git credentials

CHANGELOG.md, lib/react_on_rails/json_output.rb, lib/react_on_rails/utils.rb, spec/react_on_rails/json_output_spec.rb, spec/react_on_rails/utils_spec.rb
I noticed that JsonOutput.escape had a workaround for Rails < 4.1.1. Since the minimum supported Rails version for the gem is greater than that, it doesn't seem like this needs to be there. 
Addititionally, I removed the `Utils.rails_version_less_than_4_1_1` method since that was the only place it was used
N/A
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1580)
=> Remove JsonOutput.escape workaround for Rails < 4.1.1

node_package/src/types/index.ts
- Before: https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgIilQ3wG4AoUSWRYmAeQDsEVgAbAZzm1wKPRgBaCI0FRWnMpXDR4Ab0QSOAYREwkAD3gBfbjjyE6w0ePYcA9IwgATJAH0w6ANYoA5knNtgAI3MwAnmBIHFLkaCIc8MgCqjKMSIwwACrBMABctAIAdABiygA8CuqRGZFQwIyucNoAfHAAvHAAFGA4YBwAlA11+dbAAG41cq0Q7VnFMNr55n2DFOGMkbSMtlA5AK6MGMAiKUuNLW0cGUWppTDlldUANHCmnKqJmjAA-BksZo-qWl31dU0KIgrJBEawACRgIDYGXwE3w1Q6FHI5nMcACQTgIJwUHI0QwTA+nCyRFcwEiIIBmQwsUg8USexgt2QwLWm22u1SCNIQA
- After: https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgIilQ3wG4AoUSWRYmAeQDsEVgAbAZzm1wKPRgBaCI0FRWnMpXDR4Ab0QSOAYREwkAD3gBfbjjyE6w0ePYcA9IwgATJAH0w6ANYoA5knNtgAI3MwAnmBIHPjk0tTwAUFwCqoyjEiMMAAqgUhwujx4AOT8GNkU5ObmcABiwBpI1nAwABbAXFFI5E20AnGQCUlwALxwHSKJKWkAPCiM-gB8cAA+cBwwUMCMroWtyO24nUP0UMiMtlClAK6MGMAivW0YA13wc-uHJ2c …
=> Fix TS types

CHANGELOG.md, node_package/src/types/index.ts
Incorrect RailsContext property types have been corrected.
- ~[ ] Add/update test to cover these changes~
- ~[ ] Update documentation~
_Add the CHANGELOG entry at the top of the file._
_Remove this paragraph and mention any other important and relevant information such as benchmarks._
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1585)
=> fix RailsContext type

CHANGELOG.md, node_package/src/ReactOnRails.ts
This PR exposes all types of React on Rails. There are two main reasons for this:
Firstly, I frequently use types such as `RenderFunction` and `RailsContext` and would like to import them with minimal code:
```diff
- import { RenderFunction, RailsContext } from "react-on-rails/node_package/lib/types";
+ import { RenderFunction, RailsContext } from "react-on-rails";
```
Additionally, since [`railsContext` is customizable](https://www.shakacode.com/react-on-rails/docs/guides/render-functions-and-railscontext/#customization-of-the-rails_context), exposing the `RailsContext` type allows for extensions like the following:
`react-on-rails.d.ts`:
```ts
declare module "react-on-rails" {
interface RailsContext {
key1: string;
key2: string;
}
}
export {};
```
_Remove this line after checking all …
=> exposes all types

CHANGELOG.md
Minor edits
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1587)
=> Simplify recent changelog entries

Gemfile.development_dependencies, lib/react_on_rails/locales/base.rb, spec/dummy/spec/rails_helper.rb, spec/dummy/spec/system/integration_spec.rb
- Fixed the version of `sqlite3` to be below `1.7.0` since [the native gem support for Ruby 2.7 ended in this version.](https://github.com/sparklemotion/sqlite3-ruby/blob/main/CHANGELOG.md#170--2023-12-27)
- Customized selenium driver to use `headless=new` option. More information: [Headless is Going Away!](https://www.selenium.dev/blog/2023/headless-is-going-away/)
- Linter fixes
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1593)
=> Fix CI failure

CHANGELOG.md, lib/generators/react_on_rails/base_generator.rb
Recently `css-minimizer-webpack-plugin` [released v6.0.0](https://github.com/webpack-contrib/css-minimizer-webpack-plugin/releases/tag/v6.0.0) in which the minimum required Node version is 18.
We install this package in our generator, and we need this PR to ensure our generator doesn't break in an environment with an older Node.
~⚠️  We may need to make a release after this merge.~
~Alternatively, we can bump our Nodejs support to v18 (the current LTS)~
I have change the generator so that it limits the version of this package unless we use Node v18+.
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1598)
=> Restrict css-minimizer-webpack-plugin version in the generator unless using Node v18+

CHANGELOG.md, lib/react_on_rails/configuration.rb, lib/react_on_rails/webpacker_utils.rb, spec/dummy/spec/rake/assets_precompile_rake_spec.rb, spec/react_on_rails/configuration_spec.rb, spec/react_on_rails/generators/dev_tests_generator_spec.rb, spec/react_on_rails/generators/install_generator_spec.rb, spec/react_on_rails/support/shared_examples/react_no_redux_generator_examples.rb, spec/react_on_rails/support/shared_examples/react_with_redux_generator_examples.rb
This PR prevents displaying the Shakapcker 7+ deprecation message for:
- `webpacker_precompile?`
- `webpacker:clean` rake task
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1592)
=> Prevent Shakapacker v7 deprecation messages

Gemfile.development_dependencies, react_on_rails.gemspec, spec/dummy/Gemfile
gemspec development dependencies don't get installed by CI so this PR moves squlite from the gemspec to the Gemfile.development_dependencies file.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1613)
=> CI Fix for sqlite

docs/getting-started.md, docs/guides/installation-into-an-existing-rails-app.md, docs/guides/tutorial.md
_Remove this paragraph and provide a general description of the code changes in your pull
request... were there any bugs you had fixed? If so, mention them. If
these bugs have open GitHub issues, be sure to tag them here as well,
to keep the conversation linked together._
_Add the CHANGELOG entry at the top of the file._
_Remove this paragraph and mention any other important and relevant information such as benchmarks._
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1662)
=> Fix bad documentation links

CHANGELOG.md, Gemfile.lock, docs/guides/how-to-use-different-files-for-client-and-server-rendering.md, docs/javascript/code-splitting.md, lib/generators/react_on_rails/dev_tests_generator.rb, lib/generators/react_on_rails/templates/base/base/app/javascript/packs/registration.js.tt, lib/react_on_rails/packs_generator.rb, node_package/src/ReactOnRails.full.ts, script/convert, spec/dummy/app/views/pages/client_side_hello_world.html.erb, spec/dummy/app/views/pages/server_side_hello_world.html.erb, spec/dummy/app/views/pages/server_side_redux_app.html.erb, spec/dummy/app/views/pages/server_side_redux_app_cached.html.erb, spec/dummy/app/views/pages/xhr_refresh.html.erb, spec/dummy/client/app/startup/HelloWorldRehydratable.jsx, spec/dummy/client/app/startup/ReduxSharedStoreApp.client.jsx, spec/dummy/client/app/startup/ReduxSharedStoreApp.server.jsx, spec/dummy/spec/packs_generator_spec.rb
Since we added `react-on-rails/client` path in 14.2.0, this PR switches to it in generated packs. 
Equivalent to #1703 in 15.0.0 prerelease.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shakacode/react_on_rails/1731)
=> Update `react-on-rails` import to `/client` in 14.2.x
